import Link from "next/link";
import { School } from "lucide-react";
import { getAcademicClassList } from "@/lib/academic";
import { addStandardClasses, createSchoolClass } from "../academic-actions";

export const dynamic = "force-dynamic";

export default async function ClassesPage({ searchParams }: { searchParams: Promise<{ year?: string }> }) {
  const { year } = await searchParams;
  const { years, selectedYearId, classes } = await getAcademicClassList(year);
  const selectedYear = years.find((item) => item.id === selectedYearId);

  return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><header><h1 className="text-3xl font-bold">Classes & Sections</h1><p className="mt-2 text-slate-600">Choose an academic year, then review sections, students, and class-teacher coverage.</p></header>
    {years.length ? <form className="flex flex-col gap-3 rounded-3xl border bg-white p-6 shadow-sm sm:flex-row sm:items-end"><label className="flex-1 font-semibold">Academic year<select name="year" defaultValue={selectedYearId} className="mt-2 w-full rounded-xl border px-4 py-3">{years.map((item) => <option key={item.id} value={item.id}>{item.name}{item.current ? " (Current)" : ""}</option>)}</select></label><button className="rounded-xl border px-5 py-3 font-semibold">Show year</button></form> : null}
    {selectedYearId && <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Add a class to {selectedYear?.name}</h2><div className="mt-4 grid gap-4 md:grid-cols-[1fr_auto_auto]"><form action={createSchoolClass} className="contents"><input type="hidden" name="academicYearId" value={selectedYearId}/><input name="name" required placeholder="Class name, for example Class 3" className="rounded-xl border px-4 py-3"/><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Add class</button></form><form action={addStandardClasses}><input type="hidden" name="academicYearId" value={selectedYearId}/><button className="w-full rounded-xl border border-blue-200 px-5 py-3 font-bold text-blue-700">Add standard classes</button></form></div></section>}
    {classes.length ? <div className="grid gap-5 xl:grid-cols-2">{classes.map((item) => <article key={item.id} className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><School className="h-8 w-8 text-blue-600"/><h2 className="mt-3 text-xl font-bold">{item.name}</h2><p className="mt-1 text-sm text-slate-600">{item.sections.length} active sections · {item._count.enrollments} active enrolments</p></div><Link href={`/school-dashboard/classes/${item.id}`} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Manage class</Link></div>{item.sections.length ? <ul className="mt-5 divide-y rounded-2xl border">{item.sections.map((section) => <li key={section.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-semibold">Section {section.name}</p><p className="text-sm text-slate-500">{section._count.enrollments} students</p></div><p className={`text-sm font-semibold ${section.teacherAssignments[0] ? "text-emerald-700" : "text-amber-700"}`}>{section.teacherAssignments[0]?.teacher.user.name || "No class teacher"}</p></li>)}</ul> : <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm text-amber-800">No active sections. Open this class to add the first section.</p>}</article>)}</div> : <div className="rounded-3xl border bg-white p-14 text-center"><h2 className="text-xl font-bold">{years.length ? "No classes in this year" : "No academic year available"}</h2><p className="mt-2 text-slate-500">{years.length ? "Add one class or use the standard class list." : "Create an academic year before adding classes."}</p>{!years.length ? <Link href="/school-dashboard/academic-years" className="mt-5 inline-flex rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Set up academic year</Link> : null}</div>}
  </main>;
}
