import Link from "next/link";
import { School } from "lucide-react";
import { getAcademicClassList } from "@/lib/academic";
import { addStandardClasses, createSchoolClass } from "../academic-actions";

export const dynamic = "force-dynamic";
export default async function ClassesPage({searchParams}:{searchParams:Promise<{year?:string}>}) { const {year}=await searchParams; const {years,selectedYearId,classes}=await getAcademicClassList(year); return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><header><h1 className="text-3xl font-bold">Classes & Sections</h1><p className="mt-2 text-slate-600">Choose a year, add classes, then open a class to set up sections and subjects.</p></header>
  <form className="rounded-3xl border bg-white p-6 shadow-sm"><label className="font-semibold">Academic year<select name="year" defaultValue={selectedYearId} className="ml-4 rounded-xl border px-4 py-3" onChange={undefined}>{years.map(item=><option key={item.id} value={item.id}>{item.name}{item.current?" (Current)":""}</option>)}</select></label><button className="ml-3 rounded-xl border px-4 py-3 font-semibold">Show</button></form>
  {selectedYearId&&<div className="grid gap-4 rounded-3xl border bg-white p-6 shadow-sm md:grid-cols-[1fr_auto_auto]"><form action={createSchoolClass} className="contents"><input type="hidden" name="academicYearId" value={selectedYearId}/><input name="name" required placeholder="Class name, for example Class 3" className="rounded-xl border px-4 py-3"/><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Add class</button></form><form action={addStandardClasses}><input type="hidden" name="academicYearId" value={selectedYearId}/><button className="w-full rounded-xl border border-blue-200 px-5 py-3 font-bold text-blue-700">Add standard classes</button></form></div>}
  {classes.length?<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{classes.map(item=><Link key={item.id} href={`/school-dashboard/classes/${item.id}`} className="rounded-3xl border bg-white p-6 shadow-sm transition hover:border-blue-300"><School className="h-8 w-8 text-blue-600"/><h2 className="mt-4 text-xl font-bold">{item.name}</h2><p className="mt-2 text-slate-600">{item.sections.length} sections · {item._count.enrollments} enrolments</p><p className="mt-5 font-semibold text-blue-700">Manage sections and subjects →</p></Link>)}</div>:<div className="rounded-3xl border bg-white p-14 text-center"><h2 className="text-xl font-bold">No classes in this year</h2><p className="mt-2 text-slate-500">Add one class or use the standard class list.</p></div>}</main> }
