import Link from "next/link";
import ActivationCodeIssuer from "@/components/onboarding/ActivationCodeIssuer";
import { changeStudentEnrollment, updateStudent } from "@/app/school-dashboard/academic-actions";
import { getStudent } from "@/lib/academic";

const input = "rounded-xl border px-4 py-3";
export default async function StudentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { student, years } = await getStudent(id);
  const update = updateStudent.bind(null, id), enrol = changeStudentEnrollment.bind(null, id);
  return <main className="space-y-7 p-4 sm:p-6 lg:p-8">
    <header><h1 className="text-3xl font-bold">{student.name}</h1><p className="mt-2 text-slate-600">Admission number {student.admissionNumber}</p><Link className="mt-4 inline-block rounded-xl border border-blue-200 px-4 py-2 font-bold text-blue-700" href={`/school-dashboard/students/${student.id}/guardians`}>Manage parents / guardians</Link></header>
    <form action={update} className="grid gap-4 rounded-3xl border bg-white p-6 shadow-sm md:grid-cols-2"><label className="font-semibold">Name<input name="name" required defaultValue={student.name} className={`mt-2 ${input}`}/></label><label className="font-semibold">Email (required for activation)<input name="email" type="email" defaultValue={student.email??""} className={`mt-2 ${input}`}/></label><label className="font-semibold">Date of birth<input name="dateOfBirth" type="date" defaultValue={student.dateOfBirth?.toISOString().slice(0,10)??""} className={`mt-2 ${input}`}/></label><label className="font-semibold">Gender<input name="gender" defaultValue={student.gender??""} className={`mt-2 ${input}`}/></label><label className="flex items-center gap-3"><input name="active" type="checkbox" defaultChecked={student.active}/> Student is active</label><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Save student details</button></form>
    <ActivationCodeIssuer studentId={student.id} eligible={student.active&&!student.userId&&Boolean(student.email)}/>
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-2xl font-bold">Class enrolment</h2><form action={enrol} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><select name="academicYearId" required className={input}><option value="">Academic year</option>{years.map(year=><option key={year.id} value={year.id}>{year.name}</option>)}</select><select name="schoolClassId" required className={input}><option value="">Class</option>{years.flatMap(year=>year.classes.map(item=><option key={item.id} value={item.id}>{year.name} — {item.name}</option>))}</select><select name="sectionId" required className={input}><option value="">Section</option>{years.flatMap(year=>year.classes.flatMap(item=>item.sections.map(section=><option key={section.id} value={section.id}>{year.name} — {item.name}{section.name}</option>)))}</select><input name="rollNumber" placeholder="Roll number" className={input}/><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Save enrolment</button></form><div className="mt-7 space-y-3">{student.enrollments.map(item=><div key={item.id} className="rounded-2xl bg-slate-50 p-4"><strong>{item.academicYear.name}: {item.schoolClass.name}{item.section.name}</strong><p className="mt-1 text-sm text-slate-500">{item.rollNumber?`Roll ${item.rollNumber} · `:""}{item.status.toLowerCase()}</p></div>)}</div></section>
  </main>;
}
