"use server";
import { revalidatePath } from "next/cache";
import { AcademicPlannerItemStatus, AcademicPlannerItemType } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requireSchool } from "@/lib/school-dashboard";
import { requireSchoolFeature } from "@/lib/school-feature-access";

function dateValue(value: FormDataEntryValue | null) { const date = new Date(String(value ?? "")); if (Number.isNaN(date.getTime())) throw new Error("Enter a valid date and time."); return date; }
export async function createSchoolPlannerItem(formData:FormData){const school=await requireSchool();await requireSchoolFeature("PLANNER");const year=await prisma.academicYear.findFirst({where:{schoolId:school.id,current:true,active:true},select:{id:true}});if(!year)throw new Error("Select a current academic year first.");const title=String(formData.get("title")??"").trim();const type=String(formData.get("type")??"") as AcademicPlannerItemType;const date=dateValue(formData.get("date"));if(!title||title.length>180||!["NOTICE","HOLIDAY","EVENT"].includes(type))throw new Error("Enter a valid title and planner type.");await prisma.academicPlannerItem.create({data:{schoolId:school.id,academicYearId:year.id,type,title,description:String(formData.get("description")??"").trim()||null,fixedDate:type==="HOLIDAY"||formData.get("fixedDate")==="on",originalDate:date,currentDate:date,status:"PLANNED"}});revalidatePath("/school-dashboard");revalidatePath("/school-dashboard/planner");}
export async function updateSchoolPlannerStatus(formData:FormData){const school=await requireSchool();await requireSchoolFeature("PLANNER");const id=String(formData.get("id")??"");const status=String(formData.get("status")??"") as AcademicPlannerItemStatus;if(!["PLANNED","IN_PROGRESS","COMPLETED","CANCELLED"].includes(status))throw new Error("Invalid planner status.");const item=await prisma.academicPlannerItem.findFirst({where:{id,schoolId:school.id,sectionId:null,type:{in:["NOTICE","HOLIDAY","EVENT"]}}});if(!item)throw new Error("Planner item not found.");await prisma.academicPlannerItem.update({where:{id},data:{status,completedAt:status==="COMPLETED"?new Date():null}});revalidatePath("/school-dashboard");revalidatePath("/school-dashboard/planner");}
export async function rescheduleSchoolPlannerItem(formData:FormData){const school=await requireSchool();await requireSchoolFeature("PLANNER");const id=String(formData.get("id")??"");const date=dateValue(formData.get("date"));const reason=String(formData.get("reason")??"").trim();const item=await prisma.academicPlannerItem.findFirst({where:{id,schoolId:school.id,sectionId:null,type:{in:["NOTICE","EVENT"]}}});if(!item||item.fixedDate||!reason)throw new Error("This item cannot be rescheduled without a reason.");await prisma.$transaction(async tx=>{await tx.academicPlannerItem.update({where:{id},data:{currentDate:date,status:"RESCHEDULED"}});await tx.academicPlannerReschedule.create({data:{plannerItemId:id,fromDate:item.currentDate,toDate:date,reason,createdByUserId:school.userId}})});revalidatePath("/school-dashboard");revalidatePath("/school-dashboard/planner");}
