"use client";

import { useMemo, useState, useTransition } from "react";
import { Plus, Trash2 } from "lucide-react";
import { saveBuilderDraft } from "@/app/teacher-dashboard/ai/actions";
import { AcademicOptions, Field, inputClass, questionTypes, Section } from "./BuilderFields";

type Row = { id: number; type: string; count: number; marks: number };
type Chapter = { id: number; name: string; marks: number };
const nextId = () => Date.now() + Math.random();

export default function QuestionPaperBuilder({ options }: { options: AcademicOptions }) {
  const [academic, setAcademic] = useState({ classId: "", subjectId: "", bookId: "", chapterRange: "" });
  const [settings, setSettings] = useState({ title: "", board: "CBSE", language: "English", duration: 60, totalMarks: 40, difficulty: "Balanced" });
  const [rows, setRows] = useState<Row[]>([{ id: nextId(), type: "MCQ", count: 10, marks: 1 }]);
  const [chapters, setChapters] = useState<Chapter[]>([]);
  const [chapterName, setChapterName] = useState("");
  const [distributionMode, setDistributionMode] = useState<"difficulty" | "bloom">("difficulty");
  const [distribution, setDistribution] = useState({ first: 30, second: 50, third: 20, fourth: 0 });
  const [opts, setOpts] = useState({ answerKey: true, markingScheme: true, internalChoices: false, bloomTags: false, competencyTags: false, diagrams: false, caseStudies: false });
  const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const books = options.books.filter((b) => (!academic.classId || b.classId === academic.classId) && (!academic.subjectId || b.subjectId === academic.subjectId));
  const totals = useMemo(() => ({ questions: rows.reduce((s, r) => s + r.count, 0), marks: rows.reduce((s, r) => s + r.count * r.marks, 0), chapterMarks: chapters.reduce((s, c) => s + c.marks, 0), distribution: Object.values(distribution).reduce((s, n) => s + n, 0) }), [rows, chapters, distribution]);
  const valid = Boolean(academic.classId && academic.subjectId && academic.bookId && settings.title && chapters.length && totals.marks === settings.totalMarks && totals.chapterMarks === settings.totalMarks && totals.distribution === 100);
  function equalize() { if (!chapters.length) return; const base = Math.floor(settings.totalMarks / chapters.length); let remainder = settings.totalMarks - base * chapters.length; setChapters(chapters.map((c) => ({ ...c, marks: base + (remainder-- > 0 ? 1 : 0) }))); }
  function save() { setMessage(""); startTransition(async () => { const result = await saveBuilderDraft({ tool: "Question Paper Builder", title: settings.title, configuration: JSON.stringify({ version: 1, academic, settings, blueprint: rows, chapters, distributionMode, distribution, options: opts, totals }) }); setMessage(result.message); if (result.ok && result.previewUrl) window.location.assign(result.previewUrl); }); }
  return <div className="space-y-6"><Section title="Academic selection" description="Chapters are temporary structured inputs because the current schema has no chapter model."><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Class"><select value={academic.classId} onChange={(e) => setAcademic({ ...academic, classId: e.target.value, bookId: "" })} className={inputClass}><option value="">Select class</option>{options.classes.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Subject"><select value={academic.subjectId} onChange={(e) => setAcademic({ ...academic, subjectId: e.target.value, bookId: "" })} className={inputClass}><option value="">Select subject</option>{options.subjects.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Book / Series"><select value={academic.bookId} onChange={(e) => setAcademic({ ...academic, bookId: e.target.value })} className={inputClass}><option value="">Select book</option>{books.map((x) => <option key={x.id} value={x.id}>{x.title}{x.series ? ` — ${x.series.name}` : ""}</option>)}</select></Field><Field label="Chapter range"><input value={academic.chapterRange} onChange={(e) => setAcademic({ ...academic, chapterRange: e.target.value })} placeholder="e.g. Chapters 1–5" className={inputClass}/></Field></div><div className="mt-5 flex gap-3"><input value={chapterName} onChange={(e) => setChapterName(e.target.value)} placeholder="Add individual chapter" className={`${inputClass} mt-0 max-w-xl`}/><button type="button" onClick={() => { if (chapterName.trim()) { setChapters([...chapters, { id: nextId(), name: chapterName.trim(), marks: 0 }]); setChapterName(""); } }} className="rounded-xl bg-slate-900 px-5 font-semibold text-white">Add</button></div></Section>
  <Section title="Paper settings"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><Field label="Paper title"><input value={settings.title} onChange={(e) => setSettings({ ...settings, title: e.target.value })} className={inputClass}/></Field>{(["board","language"] as const).map((key) => <Field key={key} label={key[0].toUpperCase()+key.slice(1)}><input value={settings[key]} onChange={(e) => setSettings({ ...settings, [key]: e.target.value })} className={inputClass}/></Field>)}<Field label="Duration (minutes)"><input type="number" min="1" value={settings.duration} onChange={(e) => setSettings({ ...settings, duration: Number(e.target.value) })} className={inputClass}/></Field><Field label="Total marks"><input type="number" min="1" value={settings.totalMarks} onChange={(e) => setSettings({ ...settings, totalMarks: Number(e.target.value) })} className={inputClass}/></Field><Field label="Difficulty preset"><select value={settings.difficulty} onChange={(e) => setSettings({ ...settings, difficulty: e.target.value })} className={inputClass}>{["Easy","Balanced","Challenging"].map((x) => <option key={x}>{x}</option>)}</select></Field></div></Section>
  <Section title="Question blueprint"><div className="overflow-x-auto"><table className="w-full min-w-[720px]"><thead><tr className="text-left text-sm text-slate-500"><th className="pb-3">Question type</th><th>Questions</th><th>Marks each</th><th>Section total</th><th></th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="py-3 pr-3"><select value={row.type} onChange={(e) => setRows(rows.map((r) => r.id === row.id ? { ...r, type: e.target.value } : r))} className={inputClass}>{questionTypes.map((x) => <option key={x}>{x}</option>)}</select></td>{(["count","marks"] as const).map((key) => <td key={key} className="pr-3"><input type="number" min="1" value={row[key]} onChange={(e) => setRows(rows.map((r) => r.id === row.id ? { ...r, [key]: Number(e.target.value) } : r))} className={`${inputClass} w-28`}/></td>)}<td className="font-bold">{row.count * row.marks}</td><td><button aria-label="Remove row" onClick={() => setRows(rows.filter((r) => r.id !== row.id))} className="text-red-600"><Trash2 className="h-5 w-5"/></button></td></tr>)}</tbody></table></div><button onClick={() => setRows([...rows, { id: nextId(), type: "Short answer", count: 1, marks: 2 }])} className="mt-4 inline-flex rounded-xl border px-4 py-2 font-semibold"><Plus className="mr-2 h-4 w-4"/>Add question type</button><p className={`mt-4 font-semibold ${totals.marks === settings.totalMarks ? "text-green-700" : "text-red-600"}`}>{totals.questions} questions · {totals.marks}/{settings.totalMarks} marks</p></Section>
  <Section title="Chapter weightage"><div className="space-y-3">{chapters.map((c) => <div key={c.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="flex-1 font-medium">{c.name}</span><input aria-label={`Marks for ${c.name}`} type="number" min="0" value={c.marks} onChange={(e) => setChapters(chapters.map((x) => x.id === c.id ? { ...x, marks: Number(e.target.value) } : x))} className="w-24 rounded-lg border p-2"/><button onClick={() => setChapters(chapters.filter((x) => x.id !== c.id))}><Trash2 className="h-4 w-4 text-red-600"/></button></div>)}</div><div className="mt-4 flex items-center gap-4"><button onClick={equalize} className="rounded-xl border px-4 py-2 font-semibold">Equal distribution</button><span className={totals.chapterMarks === settings.totalMarks ? "text-green-700" : "text-red-600"}>{totals.chapterMarks}/{settings.totalMarks} marks</span></div></Section>
  <Section title="Difficulty / Bloom distribution"><div className="flex gap-3"><button onClick={() => setDistributionMode("difficulty")} className={`rounded-xl px-4 py-2 ${distributionMode === "difficulty" ? "bg-blue-600 text-white" : "border"}`}>Difficulty</button><button onClick={() => setDistributionMode("bloom")} className={`rounded-xl px-4 py-2 ${distributionMode === "bloom" ? "bg-blue-600 text-white" : "border"}`}>Bloom</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(distributionMode === "difficulty" ? ["Easy","Medium","Difficult"] : ["Remember","Understand","Apply","Analyse"]).map((label, index) => { const key = (["first","second","third","fourth"] as const)[index]; return <Field key={label} label={`${label} %`}><input type="number" min="0" max="100" value={distribution[key]} onChange={(e) => setDistribution({ ...distribution, [key]: Number(e.target.value) })} className={inputClass}/></Field>; })}</div><p className={`mt-4 font-semibold ${totals.distribution === 100 ? "text-green-700" : "text-red-600"}`}>Total: {totals.distribution}%</p></Section>
  <Section title="Options"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(opts).map(([key,value]) => <label key={key} className="flex items-center gap-3 rounded-xl border p-4"><input type="checkbox" checked={value} onChange={(e) => setOpts({ ...opts, [key]: e.target.checked })}/><span className="font-medium">{key.replace(/([A-Z])/g," $1")}</span></label>)}</div></Section>
  <Section title="Review"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Chapters" value={chapters.map((x) => x.name).join(", ") || "None"}/><Summary label="Questions" value={String(totals.questions)}/><Summary label="Marks" value={`${totals.marks}/${settings.totalMarks}`}/><Summary label="Duration" value={`${settings.duration} minutes`}/></div><div className="mt-5 grid gap-4 lg:grid-cols-3"><Summary label="Question distribution" value={rows.map((x) => `${x.type}: ${x.count} × ${x.marks}`).join("; ")}/><Summary label="Chapter weightage" value={chapters.map((x) => `${x.name}: ${x.marks}`).join("; ")}/><Summary label={distributionMode} value={`${totals.distribution}% allocated`}/></div></Section>
  {message && <div role="status" className="rounded-xl border border-blue-200 bg-blue-50 p-4 font-semibold text-blue-800">{message}</div>}<button disabled={!valid || pending} onClick={save} className="w-full rounded-2xl bg-blue-600 px-6 py-4 text-lg font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{pending ? "Saving draft…" : "Generate & save draft"}</button>{!valid && <p className="text-center text-sm text-red-600">Complete academic fields and ensure paper marks, chapter marks, and distribution totals are valid.</p>}</div>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 break-words font-semibold">{value || "—"}</p></div>; }
