import { Award, BookOpen, Calendar, GraduationCap, Mail, Phone, School, Shield, User } from "lucide-react";
import { requireTeacher } from "@/lib/teacher-dashboard";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const metadata = { title: "My Profile | Bluegate Teacher Dashboard" };

export default async function ProfilePage() {
  const teacher = await requireTeacher();
  return <div className="space-y-8 p-4 sm:p-6 lg:p-8"><div><h1 className="text-3xl font-bold sm:text-4xl">My Profile</h1><p className="mt-2 text-slate-600">Your teacher and school details.</p></div><section className="rounded-3xl bg-gradient-to-r from-blue-700 to-blue-900 p-8 text-white shadow-xl"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="flex h-24 w-24 items-center justify-center rounded-full bg-white"><User className="h-12 w-12 text-blue-700" /></div><div><h2 className="text-3xl font-bold">{teacher.user.name}</h2><p className="mt-2 text-blue-100">{teacher.designation}</p><span className={`mt-4 inline-flex rounded-full px-3 py-1 text-sm font-semibold ${teacher.verified ? "bg-green-500" : "bg-amber-500"}`}>{teacher.verified ? "Verified Teacher" : "Verification Pending"}</span></div></div></section><div className="grid gap-6 lg:grid-cols-2"><Card title="Personal Information"><Info icon={Mail} label="Email" value={teacher.user.email} /><Info icon={Phone} label="Phone" value={teacher.user.phone ?? "Not provided"} /><Info icon={Calendar} label="Member since" value={teacher.user.createdAt.toLocaleDateString("en-IN", { month: "long", year: "numeric" })} /></Card><Card title="School Information"><Info icon={School} label="School" value={teacher.school?.schoolName ?? teacher.schoolName} /><Info icon={School} label="Link status" value={teacher.school ? "Linked" : "Not linked"} /><Info icon={GraduationCap} label="Designation" value={teacher.designation} /><Info icon={BookOpen} label="Subject" value={teacher.subject} /><Info icon={Award} label="Classes" value={teacher.classes} /></Card></div><section className="flex items-start gap-4 rounded-3xl border bg-white p-7 shadow-sm"><Shield className={`h-10 w-10 ${teacher.verified ? "text-green-600" : "text-amber-500"}`} /><div><h2 className="text-xl font-bold">Account status</h2><p className="mt-2 text-slate-600">{teacher.verified ? "Your teacher account is verified." : "Your teacher account is awaiting verification."}</p></div></section></div>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border bg-white p-7 shadow-sm"><h2 className="text-2xl font-bold">{title}</h2><div className="mt-6 space-y-5">{children}</div></section>; }
function Info({ icon: Icon, label, value }: { icon: typeof Mail; label: string; value: string | null }) { return <div className="flex gap-4"><span className="rounded-xl bg-blue-50 p-3 text-blue-700"><Icon className="h-5 w-5" /></span><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 font-semibold">{value ?? "Not provided"}</p></div></div>; }
