"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Send } from "lucide-react";

type ChatMessage = { id: string; text: string; kind: string; senderUserId: string; createdAt: string; pinnedAt: string | null; sender: { name: string; role: string }; replyTo: { id: string; text: string; sender: { name: string } } | null };

export default function StudentClassChat({ compact = false }: { compact?: boolean }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [text, setText] = useState(""); const [error, setError] = useState(""); const [sending, setSending] = useState(false); const [currentUserId, setCurrentUserId] = useState(""); const [replyTo, setReplyTo] = useState<ChatMessage | null>(null);
  const refresh = useCallback(async () => { const response = await fetch("/api/student/class-chat", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessages(data.messages); setCurrentUserId(data.currentUserId); }, []);
  useEffect(() => { const initial = window.setTimeout(() => refresh().catch((e) => setError(e.message)), 0); const timer = window.setInterval(() => refresh().catch(() => undefined), 15000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [refresh]);
  async function submit(event: FormEvent) { event.preventDefault(); if (!text.trim() || sending) return; const value = text; setText(""); setSending(true); setError(""); try { const response = await fetch("/api/student/class-chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: value, replyToId: replyTo?.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setReplyTo(null); await refresh(); } catch (e) { setText(value); setError(e instanceof Error ? e.message : "Message could not be sent."); } finally { setSending(false); } }
  async function remove(id: string) { const response = await fetch(`/api/student/class-chat/${id}`, { method: "DELETE" }); if (response.ok) await refresh(); else setError((await response.json()).error); }
  return <section className="flex min-h-0 flex-col overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold text-slate-900">Class Chat</h2><p className="text-xs text-emerald-600">● Your section</p></div>{compact && <Link href="/student-dashboard/my-class/chat" className="text-sm font-semibold text-blue-600">Open full chat</Link>}</div><div aria-live="polite" className={`space-y-4 overflow-y-auto p-5 ${compact ? "h-72" : "h-[55vh]"}`}>{messages.length ? messages.map((message) => <article key={message.id} className="rounded-2xl bg-slate-50 p-3"><div className="flex justify-between gap-3"><strong className="text-sm">{message.sender.name} <span className="font-normal text-slate-400">· {message.sender.role.toLowerCase()}</span></strong><time className="text-xs text-slate-400">{new Date(message.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></div>{message.replyTo && <p className="mt-2 border-l-2 border-blue-300 pl-2 text-xs text-slate-500">{message.replyTo.sender.name}: {message.replyTo.text}</p>}<p className="mt-1 break-words text-sm text-slate-700">{message.text}</p><div className="mt-2 flex gap-3 text-xs font-semibold"><button onClick={() => setReplyTo(message)} className="text-blue-600">Reply</button>{message.senderUserId === currentUserId && <button onClick={() => remove(message.id)} className="text-red-500">Delete</button>}</div></article>) : <p className="py-12 text-center text-sm text-slate-500">No messages yet. Start the class conversation.</p>}</div><form onSubmit={submit} className="border-t p-4">{replyTo && <div className="mb-2 flex items-center justify-between rounded-xl bg-blue-50 px-3 py-2 text-xs"><span>Replying to {replyTo.sender.name}</span><button type="button" onClick={() => setReplyTo(null)}>Cancel</button></div>}<div className="flex gap-2"><input value={text} onChange={(e) => setText(e.target.value)} maxLength={2000} aria-label="Message" placeholder="Message your class…" className="min-w-0 flex-1 rounded-2xl border px-4 py-3 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /><button disabled={sending || !text.trim()} aria-label="Send message" className="rounded-2xl bg-blue-600 p-3 text-white disabled:opacity-50"><Send className="h-5 w-5" /></button></div>{error && <p className="mt-2 text-sm text-red-600">{error}</p>}</form></section>;
}
