import Link from "next/link";
// Today’s Schedule
import { Activity, BarChart3, BookOpen, CalendarCheck2, CalendarClock, CalendarDays, ClipboardCheck, GraduationCap, Megaphone, School, UserPlus, Users, UserRoundPlus, UsersRound } from "lucide-react";
import { getSchoolHomeData } from "@/lib/school-dashboard";
import { SchoolActivityRow, SchoolEmptyState, SchoolFeatureTile, SchoolMetricTile, SchoolSection, SchoolStatusTile, schoolTypography } from "@/components/school/SchoolUI";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function SchoolDashboardPage() {
  const data = await getSchoolHomeData();
  return <main className="mx-auto max-w-[1600px] space-y-5 p-4 sm:p-6 lg:p-7">
    <header className="flex flex-col gap-4 rounded-xl border border-blue-100 bg-gradient-to-br from-blue-50 via-white to-indigo-50 p-5 shadow-sm sm:flex-row sm:items-end sm:justify-between sm:p-6"><div><p className="mb-2 text-[0.68rem] font-bold uppercase tracking-[0.2em] text-blue-700">School overview</p><h1 className={schoolTypography.pageTitle}>Your school at a glance</h1><p className={`mt-2 max-w-2xl ${schoolTypography.body}`}>A clear view of people, attendance, planning, and the next actions for your school team.</p></div><Link href="/school-dashboard/planner" className="inline-flex w-fit items-center rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-blue-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2">Open planner</Link></header>
    <section aria-label="School summary" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SchoolMetricTile icon={GraduationCap} value={data.stats.students} label="Students" tone="blue" href="/school-dashboard/students" /><SchoolMetricTile icon={Users} value={data.stats.staff} label="Teachers & staff" tone="teal" href="/school-dashboard/teachers" /><SchoolMetricTile icon={School} value={`${data.stats.classes} / ${data.stats.sections}`} label="Classes / sections" tone="violet" href="/school-dashboard/classes" /><SchoolMetricTile icon={CalendarCheck2} value={data.stats.attendance == null ? "-" : `${data.stats.attendance}%`} label="Attendance today" tone="amber" detail={data.stats.attendance == null ? "No attendance submitted yet" : undefined} href="/school-dashboard/attendance" /></section>
    <section aria-label="Attendance status" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SchoolStatusTile icon={Users} value={data.stats.attendancePresent} label="Present" tone="teal" href="/school-dashboard/attendance" /><SchoolStatusTile icon={Users} value={data.stats.attendanceAbsent} label="Absent" tone="rose" href="/school-dashboard/attendance" /><SchoolStatusTile icon={CalendarClock} value={data.stats.pendingClasses} label="Pending classes" tone="violet" href="/school-dashboard/attendance" /><SchoolStatusTile icon={ClipboardCheck} value={data.stats.pendingCorrections} label="Pending corrections" tone="amber" href="/school-dashboard/attendance" /></section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(19rem,.65fr)]"><div className="space-y-5">
      <SchoolSection title="Academic Performance" action={{ label: "View reports", href: "/school-dashboard/reports" }}>{data.performance.measured ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Excellent", data.performance.excellent, "bg-emerald-50 text-emerald-700"], ["Good", data.performance.good, "bg-blue-50 text-blue-700"], ["Average", data.performance.average, "bg-amber-50 text-amber-700"], ["Needs support", data.performance.support, "bg-rose-50 text-rose-700"]].map(([label, value, tone]) => <div key={String(label)} className={`rounded-xl p-4 text-center ${tone}`}><strong className="text-2xl">{value}</strong><p className="mt-1 text-xs font-semibold">{label}</p></div>)}</div> : <SchoolEmptyState icon={BarChart3} title="Performance will appear here" description="Performance summaries will become available after student assessment analytics are recorded." action={{ label: "Open reports", href: "/school-dashboard/reports" }} />}</SchoolSection>
      <SchoolSection title="Important Notices" action={{ label: "View all", href: "/school-dashboard/planner?view=notices" }}>{data.notices.length ? <div>{data.notices.map((item) => <div key={item.id} className="flex gap-3 border-b border-slate-100 py-3 last:border-0"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-rose-100 text-rose-700"><Megaphone className="h-4 w-4" aria-hidden="true" /></span><div className="min-w-0"><strong className="text-sm font-bold text-slate-800">{item.title}</strong><p className={`mt-1 line-clamp-2 ${schoolTypography.helper}`}>{item.description || item.type}</p></div></div>)}</div> : <SchoolEmptyState icon={Megaphone} title="No active notices" description="Publish a notice from the planner when your school team needs to share an update." action={{ label: "Create a notice", href: "/school-dashboard/planner?view=notices" }} />}</SchoolSection>
      <SchoolSection title="Quick Access" description="Common school tasks, one click away."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5"><SchoolFeatureTile icon={UserPlus} label="Add student" description="Manage student records" href="/school-dashboard/students" tone="blue" /><SchoolFeatureTile icon={UserRoundPlus} label="Add teacher" description="Manage teaching staff" href="/school-dashboard/teachers" tone="teal" /><SchoolFeatureTile icon={UsersRound} label="Parents & guardians" description="Review family access" href="/school-dashboard/people?tab=parents" tone="rose" /><SchoolFeatureTile icon={Users} label="Mentors" description="Manage mentor support" href="/school-dashboard/people/mentors" tone="violet" /><SchoolFeatureTile icon={BookOpen} label="Classes & sections" description="Organise school groups" href="/school-dashboard/classes" tone="blue" /><SchoolFeatureTile icon={CalendarCheck2} label="Attendance" description="Review daily status" href="/school-dashboard/attendance" tone="amber" /><SchoolFeatureTile icon={CalendarDays} label="Planner & calendar" description="Plan school activity" href="/school-dashboard/planner" tone="teal" /><SchoolFeatureTile icon={Megaphone} label="Create notice" description="Share a school update" href="/school-dashboard/planner?view=notices" tone="rose" /><SchoolFeatureTile icon={BarChart3} label="Reports" description="View school insights" href="/school-dashboard/reports" tone="violet" /></div></SchoolSection>
      <div className="grid gap-5 lg:grid-cols-2"><SchoolSection title="Setup progress"><div className="grid gap-2 sm:grid-cols-2">{data.checklist.map((step) => <Link key={step.key} href={step.href} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2.5 text-sm transition hover:bg-blue-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"><span className="font-semibold text-slate-700">{step.label}</span><span className={step.complete ? "text-xs font-bold text-emerald-700" : "text-xs font-bold text-blue-700"}>{step.complete ? <>Complete: {step.label}</> : <>Open: {step.label}</>}</span></Link>)}</div></SchoolSection><SchoolSection title="Recent activity">{data.activities.length ? <div>{data.activities.map((item) => <SchoolActivityRow key={item.id} icon={Activity} text={item.text} at={item.at} tone="blue" />)}</div> : <SchoolEmptyState icon={Activity} title="No recent activity" description="Recent school actions will appear here as your team works." />}</SchoolSection></div>
      <SchoolSection title="At a glance"><div className="grid gap-3 sm:grid-cols-3"><Glance label="Current academic year" value={data.currentYear?.name ?? "Not selected"} /><Glance label="Upcoming planner items" value={String(data.upcoming.length)} /><Glance label="Measured performance" value={String(data.performance.measured)} /></div></SchoolSection>
    </div><aside><SchoolSection title="Today's Schedule" action={{ label: "View planner", href: "/school-dashboard/planner" }}>{data.today.length ? <div>{data.today.map((item) => <div key={item.id} className="grid grid-cols-[4.5rem_1fr] gap-3 border-b border-slate-100 py-3 last:border-0"><time className="pt-0.5 text-xs font-bold text-slate-500">{item.currentDate.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time><div><strong className="text-sm font-bold text-slate-800">{item.sectionSubject?.subject.name ?? item.title}</strong><p className={`mt-1 ${schoolTypography.helper}`}>{item.section ? `${item.section.schoolClass.name} - ${item.section.name}` : item.title}</p></div></div>)}</div> : <SchoolEmptyState icon={CalendarClock} title="Nothing scheduled today" description="Your planned classes and school events will appear here." action={{ label: "Open planner", href: "/school-dashboard/planner" }} />}</SchoolSection></aside></div>
  </main>;
}

function Glance({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-4"><p className={schoolTypography.helper}>{label}</p><strong className="mt-1 block text-lg font-bold text-slate-900">{value}</strong></div>; }
