import Link from "next/link";
import { BarChart3, BookOpen, CalendarDays, GraduationCap, Megaphone, School, UserPlus, Users } from "lucide-react";
import { getSchoolHomeData } from "@/lib/school-dashboard";
export const dynamic = "force-dynamic"; export const revalidate = 0;

export default async function SchoolDashboardPage() {
  const data = await getSchoolHomeData();
  return <main className="space-y-6 p-4 sm:p-6 lg:p-8">
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={GraduationCap} value={data.stats.students} label="Total Students" tone="blue"/><Metric icon={Users} value={data.stats.staff} label="Teachers & Staff" tone="green"/><Metric icon={School} value={`${data.stats.classes} / ${data.stats.sections}`} label="Classes / Sections" tone="purple"/><Metric icon={CalendarDays} value={data.stats.attendance == null ? "—" : `${data.stats.attendance}%`} label="Attendance Today" tone="amber" detail={data.stats.attendance == null ? "No attendance has been submitted yet." : undefined} href="/school-dashboard/attendance"/><Metric icon={Users} value={data.stats.attendancePresent} label="Present" tone="green"/><Metric icon={Users} value={data.stats.attendanceAbsent} label="Absent" tone="amber"/><Metric icon={Users} value={data.stats.pendingClasses} label="Pending Classes" tone="purple"/><Metric icon={Users} value={data.stats.pendingCorrections} label="Pending Corrections" tone="blue"/></section>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_.75fr]"><div className="space-y-6"><div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><Panel title="Academic Performance" action="View reports" href="/school-dashboard/reports">{data.performance.measured ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Excellent",data.performance.excellent,"bg-emerald-50 text-emerald-700"],["Good",data.performance.good,"bg-blue-50 text-blue-700"],["Average",data.performance.average,"bg-amber-50 text-amber-700"],["Needs Support",data.performance.support,"bg-rose-50 text-rose-700"]].map(([label,value,tone])=><div key={String(label)} className={`rounded-2xl p-4 text-center ${tone}`}><strong className="text-2xl">{value}</strong><p className="mt-1 text-xs font-semibold">{label}</p></div>)}</div> : <Empty text="Performance appears after student assessment analytics are recorded."/>}</Panel><Panel title="Important Notices" action="View all" href="/school-dashboard/planner?view=notices">{data.notices.length ? data.notices.map(item=><div key={item.id} className="flex gap-3 border-b py-3 last:border-0"><Megaphone className="mt-1 h-5 w-5 text-rose-500"/><div><strong className="text-sm">{item.title}</strong><p className="mt-1 line-clamp-2 text-xs text-slate-500">{item.description || item.type}</p></div></div>) : <Empty text="No active notices."/>}</Panel></div>
      <Panel title="Quick Access"><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-7"><Quick href="/school-dashboard/students" label="Add Student" icon={UserPlus}/><Quick href="/school-dashboard/teachers" label="Add Teacher" icon={Users}/><Quick href="/school-dashboard/people?tab=parents" label="Parents" icon={Users}/><Quick href="/school-dashboard/classes" label="Class / Section" icon={BookOpen}/><Quick href="/school-dashboard/attendance" label="Attendance" icon={CalendarDays}/><Quick href="/school-dashboard/planner?view=notices" label="Create Notice" icon={Megaphone}/><Quick href="/school-dashboard/reports" label="View Reports" icon={BarChart3}/></div></Panel>
      <Panel title="Setup progress"><div className="grid gap-2 sm:grid-cols-2">{data.checklist.map(step=><Link key={step.key} href={step.href} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{step.label}</span><span className={step.complete?"text-emerald-700":"text-blue-700"}>{step.complete ? <>Complete: {step.label}</> : <>Open: {step.label}</>}</span></Link>)}</div></Panel><Panel title="At a Glance"><div className="grid gap-3 sm:grid-cols-3"><Small label="Current academic year" value={data.currentYear?.name ?? "Not selected"}/><Small label="Upcoming planner items" value={String(data.upcoming.length)}/><Small label="Measured performance" value={String(data.performance.measured)}/></div></Panel>
    </div><aside className="space-y-6"><Panel title="Today’s Schedule" action="View planner" href="/school-dashboard/planner">{data.today.length ? data.today.map(item=><div key={item.id} className="grid grid-cols-[70px_1fr] gap-3 border-b py-3 last:border-0"><time className="text-sm font-semibold text-slate-500">{item.currentDate.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time><div><strong className="text-sm">{item.sectionSubject?.subject.name ?? item.title}</strong><p className="mt-1 text-xs text-slate-500">{item.section ? `${item.section.schoolClass.name} - ${item.section.name}` : item.title}</p></div></div>) : <Empty text="No school events or classes are scheduled today."/>}</Panel><Panel title="Recent Activities">{data.activities.length ? data.activities.map(item=><div key={item.id} className="border-b py-3 last:border-0"><p className="text-sm">{item.text}</p><time className="mt-1 block text-xs text-slate-400">{item.at.toLocaleDateString("en-IN", {day:"numeric",month:"short",year:"numeric"})}</time></div>) : <Empty text="Recent school activity will appear here."/>}</Panel></aside></div>
  </main>;
}
function Metric({icon:Icon,value,label,tone,detail,href}:{icon:typeof Users;value:number|string;label:string;tone:string;detail?:string;href?:string}){const colors:Record<string,string>={blue:"bg-blue-50 text-blue-600",green:"bg-emerald-50 text-emerald-600",purple:"bg-violet-50 text-violet-600",amber:"bg-amber-50 text-amber-600"};const content=<article className={`flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${href?"hover:border-blue-300":""}`}><span className={`grid h-14 w-14 place-items-center rounded-xl ${colors[tone]}`}><Icon/></span><div><strong className="text-2xl text-slate-950">{value}</strong><p className="text-sm font-medium text-slate-600">{label}</p>{detail&&<p className="text-xs text-slate-400">{detail}</p>}</div></article>;return href?<Link href={href}>{content}</Link>:content}
function Panel({title,children,action,href}:{title:string;children:React.ReactNode;action?:string;href?:string}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold text-slate-950">{title}</h2>{action&&href&&<Link href={href} className="text-xs font-semibold text-blue-600">{action}</Link>}</div>{children}</section>}
function Quick({href,label,icon:Icon}:{href:string;label:string;icon:typeof Users}){return <Link href={href} className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl bg-slate-50 p-3 text-center text-xs font-semibold hover:bg-blue-50 hover:text-blue-700"><Icon className="h-6 w-6 text-blue-600"/>{label}</Link>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><strong className="mt-1 block text-lg">{value}</strong></div>}
function Empty({text}:{text:string}){return <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">{text}</p>}
