import Link from "next/link";
import { AnalyticsPlaceholders, EmptyAnalytics, MetricGrid, ProgressBars, ReportHero, Timeline, displayPercent } from "@/components/analytics/AnalyticsVisuals";
import { getStudentAnalyticsReport } from "@/lib/analytics-reports";
export const dynamic = "force-dynamic"; export const revalidate = 0;
export default async function StudentReportsPage() {
  const report = await getStudentAnalyticsReport();
  if (report.state !== "READY") return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><ReportHero eyebrow="Learning reports" title="My progress" description="Your factual learning record across reading, revision, practice, assessments, and the learning assistant."/><section className="rounded-3xl border bg-white p-10 text-center shadow-sm"><h2 className="text-xl font-bold">{report.state === "LOCKED" ? "Reports are available with Premium." : "Reports are not enabled on this platform."}</h2><p className="mt-2 text-slate-600">Your learning activity remains available in its original tools.</p></section></main>;
  const s = report.summary;
  const metrics = s ? [{label:"Books completed",value:`${s.booksCompleted}/${s.booksStarted}`},{label:"Pages read",value:s.pagesRead},{label:"Study time",value:`${Math.round(s.timeStudiedSeconds/60)} min`},{label:"Current streak",value:`${s.currentStreak} days`,detail:`Longest: ${s.longestStreak} days`},{label:"Reading",value:displayPercent(s.readingPercent)},{label:"Revision",value:displayPercent(s.revisionPercent)},{label:"Practice average",value:displayPercent(s.averagePractice)},{label:"Assessment average",value:displayPercent(s.averageAssessment)},{label:"AI sessions",value:s.aiSessions},{label:"AI requests",value:s.aiRequests},{label:"Practice completion",value:displayPercent(s.practicePercent)},{label:"Assessment completion",value:displayPercent(s.assessmentPercent)}] : [];
  return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><ReportHero eyebrow={report.year} title="My learning progress" description="Stored educational metrics updated after successful learning activity. This page does not recalculate raw history."/>{report.gapEnabled?<Link href="/student-dashboard/gaps" className="inline-flex rounded-xl bg-indigo-700 px-5 py-3 font-bold text-white">My learning gaps · {report.openGapCount} open</Link>:null}{s?<><MetricGrid metrics={metrics}/><ProgressBars title="Subject completion" rows={report.subjects.map(row=>({label:row.subject.name,value:row.completionPercent,detail:`${Math.round(row.completionPercent)}% complete`}))}/><ProgressBars title="Chapter completion" rows={report.chapters.map(row=>({label:`${row.book.title} · Chapter ${row.chapter.chapterNumber}: ${row.chapter.title}`,value:row.completionPercent}))}/><Timeline rows={report.timeline}/><AnalyticsPlaceholders/></>:<EmptyAnalytics/>}</main>;
}
