import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
const read = (path: string) => readFileSync(path, "utf8");

test("mentor role has a dedicated login, route, callback home and live Auth.js eligibility check", () => { const auth = read("auth.ts"), policy = read("lib/auth-policy.ts"), proxy = read("proxy.ts"); assert.match(auth, /user\.role === "MENTOR"/); assert.match(auth, /TUTOR_PLATFORM/); assert.match(policy, /MENTOR: "\/mentor-dashboard"/); assert.match(policy, /"\/mentor-login"/); assert.match(proxy, /mentor-dashboard/); });
test("mentor assignment derives authority server-side and requires feature, plan and current enrollment", () => { const source = read("lib/mentor-assignments.ts"); assert.match(source, /requirePublisherAdmin/); assert.match(source, /requireSchool/); assert.match(source, /TUTOR_PLATFORM/); assert.match(source, /INDIVIDUAL_PREMIUM_MENTOR/); assert.match(source, /academicYear: \{ current: true, active: true \}/); assert.match(source, /pg_advisory_xact_lock/); });
test("only one active primary mentor is retained and replacement preserves history", () => { const source = read("lib/mentor-assignments.ts"), schema = read("prisma/schema.prisma"); assert.match(schema, /activePrimaryKey\s+String\?\s+@unique/); assert.match(source, /status: MentorAssignmentStatus\.ENDED/); assert.match(source, /activePrimaryKey: null/); assert.doesNotMatch(source, /deleteMany|\.delete\(/); });
test("mentor student reads start from owned assignments and current year", () => { const source = read("lib/mentor-dashboard.ts"); assert.match(source, /mentorId: mentor\.id, studentId, status: "ACTIVE"/); assert.match(source, /assignment\.academicYear\.current/); assert.match(source, /canAccessMentorAssignment/); assert.doesNotMatch(source, /student\.findMany/); });
test("student profile is read-only and never exposes teacher resources or raw learning responses", () => { const source = read("lib/mentor-dashboard.ts"), page = read("app/mentor-dashboard/students/[studentId]/page.tsx"); assert.match(source, /studentAnalytics/); assert.match(source, /studentSubjectAnalytics/); assert.match(source, /studentChapterAnalytics/); assert.match(source, /learningTimeline/); assert.doesNotMatch(source, /resource\.find|assessmentResponse|studentAiMessage/); assert.doesNotMatch(page, /fileUrl|correctAnswer|assessmentResponse|studentAiMessage/); });
test("mentor notes are append-only, typed, bounded and audited", () => { const source = read("lib/mentor-dashboard.ts"); assert.match(source, /mentorNote\.create/); assert.match(source, /NOTE_CREATED/); assert.match(source, /validMentorNote/); assert.doesNotMatch(source, /mentorNote\.update|mentorNote\.delete/); });
test("mentor remedial actions record review recommendations without changing generated paths", () => { const source = read("lib/mentor-dashboard.ts"); assert.match(source, /REMEDIAL_REVIEWED/); assert.match(source, /REMEDIAL_COMPLETION_RECOMMENDED/); assert.match(source, /PlatformFeatureKey\.REMEDIALS/); assert.doesNotMatch(source, /remedialPlan\.update|remedialStep\.update/); });
test("Student AI handoff is feature-gated and exposes no prompt, provider, model or quota", () => { const source = read("lib/mentor-dashboard.ts"); assert.match(source, /PlatformFeatureKey\.STUDENT_AI/); assert.match(source, /STUDENT_AI_LAUNCHED/); assert.doesNotMatch(source, /prompt-builder|provider-registry|student-quota|studentAiMessage/); });
test("mentor reports aggregate assigned learners only", () => { const source = read("lib/mentor-dashboard.ts"); assert.match(source, /getAssignedStudents\(\)/); assert.match(source, /completedRemedials/); assert.match(source, /openGaps/); assert.match(source, /learningTrend/); assert.match(source, /currentStreak/); });
test("sessions are placeholders with no messaging, video, chat or calling implementation", () => { const schema = read("prisma/schema.prisma"), page = read("app/mentor-dashboard/sessions/page.tsx"); assert.match(schema, /enum MentorSessionStatus[\s\S]*SCHEDULED[\s\S]*COMPLETED[\s\S]*CANCELLED/); assert.match(page, /Live meetings, chat, video and calling are intentionally absent/); assert.doesNotMatch(schema, /MentorMessage|VideoCall|ChatRoom/); });
test("mentor migration is additive, restrictive, and does not enable the publisher feature", () => { const sql = read("prisma/migrations/20260716090000_mentor_platform/migration.sql"); assert.match(sql, /ALTER TYPE "UserRole" ADD VALUE 'MENTOR'/); assert.match(sql, /CREATE TABLE "MentorStudentAssignment"/); assert.match(sql, /ON DELETE RESTRICT/); assert.match(sql, /"implemented"=true/); assert.doesNotMatch(sql, /INSERT INTO "PublisherFeature"|DROP TABLE|DROP COLUMN|DELETE FROM|TRUNCATE/i); });
