import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { canDeleteOwnSectionMessage, canModerateSectionChat, canPostSectionChat, canReadSectionChat, type SectionChatActor } from "../lib/section-chat-policy";
import { canCarryForward, carryForward } from "../lib/student-planner-policy";

const source = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const navigation = source("components/student/StudentNavigation.tsx");
const header = source("components/student/StudentHeader.tsx");
const shell = source("components/student/StudentDashboardShell.tsx");
const home = source("app/student-dashboard/page.tsx");
const data = source("lib/student-classroom-data.ts");
const chat = source("lib/student-class-chat.ts");
const notices = source("app/student-dashboard/notices/page.tsx");
const planner = source("app/student-dashboard/planner/page.tsx");
const subject = source("lib/student-subjects.ts");
const workspace = source("lib/student-workspaces.ts");
const chapter = source("app/student-dashboard/subjects/[sectionSubjectId]/chapters/[chapterId]/page.tsx");

const student: SectionChatActor = { schoolId: "s1", sectionId: "a", active: true, schoolAccessActive: true, role: "STUDENT" };
const teacher: SectionChatActor = { schoolId: "s1", sectionId: "a", active: true, schoolAccessActive: true, role: "TEACHER", officiallyAssigned: true };
const room = { schoolId: "s1", sectionId: "a" };

test("1 sidebar contains only the four final items", () => { assert.deepEqual([...navigation.matchAll(/label: "([^"]+)"/g)].map((match) => match[1]), ["Home", "My Class", "Notices", "Planner"]); });
test("2 profile exists only in avatar menu", () => { assert.match(header, /student-dashboard\/profile/); assert.doesNotMatch(navigation, /Profile/); });
test("3 chapter workspace has no global shell", () => { assert.match(shell, /student-dashboard\\\/subjects/); assert.match(shell, /return children/); });
test("4 mobile navigation uses the same four items", () => { assert.match(navigation, /grid-cols-4/); assert.match(navigation, /STUDENT_NAV_ITEMS\.map/); });
test("5 home omits book and subject grids", () => { assert.doesNotMatch(home, /StudentLibraryBookCard|StudentSubjectCard|My Books|My Subjects/); });
test("6 resume uses authorized persisted progress", () => { assert.match(data, /studentBookProgress\.findMany/); assert.match(data, /bookId: \{ in:/); });
test("7 assignment and assessment figures use student scope", () => { assert.match(data, /classroomAssignment\.findMany/); assert.match(data, /assessment\.findMany/); assert.match(data, /sectionId: identity\.enrollment\.sectionId/); });
test("8 chat preview resolves only the enrolled section room", () => { assert.match(chat, /sectionId: enrollment\.sectionId/); });
test("9 subjects originate from active section subjects", () => { assert.match(subject, /prisma\.sectionSubject\.findMany/); assert.match(subject, /active: true/); });
test("10 class teacher uses official assignment", () => { assert.match(data, /TeacherAssignmentType\.CLASS_TEACHER/); });
test("11 another section chat cannot be opened", () => { assert.equal(canReadSectionChat(student, { ...room, sectionId: "b" }), false); });
test("12 inactive enrollment actor is blocked", () => { assert.equal(canReadSectionChat({ ...student, active: false }, room), false); });
test("13 active section member can read", () => { assert.equal(canReadSectionChat(student, room), true); });
test("14 authorized section member can post", () => { assert.equal(canPostSectionChat(teacher, room), true); });
test("15 cross-school and cross-section chat is blocked", () => { assert.equal(canReadSectionChat(student, { schoolId: "s2", sectionId: "a" }), false); assert.equal(canReadSectionChat(student, { schoolId: "s1", sectionId: "b" }), false); });
test("16 no private message destination exists", () => { assert.doesNotMatch(chat, /recipient|directMessage|private/); });
test("17 moderation requires assigned non-student", () => { assert.equal(canModerateSectionChat(student, room), false); assert.equal(canModerateSectionChat(teacher, room), true); });
test("18 unread state is room and user specific", () => { assert.match(chat, /roomId_userId/); });
test("19 invalid school access cannot post", () => { assert.equal(canPostSectionChat({ ...student, schoolAccessActive: false }, room), false); });
test("20 notices use school and section applicability", () => { assert.match(data, /sectionId: null/); assert.match(data, /identity\.enrollment\.sectionId/); });
test("21 notices UI exposes no mutation controls", () => { assert.doesNotMatch(notices, /Create|Edit|Delete|POST|PATCH/); });
test("22 planner uses current academic year and section", () => { assert.match(data, /academicYearId: identity\.enrollment\.academicYearId/); assert.match(data, /sectionId = identity\.enrollment\.sectionId/); });
test("23 fixed dates never carry forward", () => { assert.equal(canCarryForward({ fixedDate: true, status: "NOT_COMPLETED", originalDate: new Date(0), currentDate: new Date(1) }), false); });
test("24 movable incomplete items retain original date and history", () => { const originalDate = new Date(0); const currentDate = new Date(1); const next = new Date(2); const result = carryForward({ fixedDate: false, status: "NOT_COMPLETED", originalDate, currentDate }, next); assert.equal(result.item.originalDate, originalDate); assert.deepEqual(result.history, { fromDate: currentDate, toDate: next }); });
test("25 planner UI exposes no mutation controls", () => { assert.doesNotMatch(planner, /Create|Edit|Delete|POST|PATCH/); });
test("26 subject lookup is restricted to enrolled active subjects", () => { assert.match(subject, /sectionId: enrollment\.sectionId/); assert.match(subject, /active: true/); });
test("27 subject chapters require the entitled subject book", () => { assert.match(workspace, /subject\.book\.id/); assert.match(workspace, /approved: true, published: true/); });
test("28 resources require student audience and entitlement", () => { assert.match(workspace, /audience: \{ in: \["STUDENT", "BOTH"\] \}/); assert.match(workspace, /schoolEntitlements/); });
test("29 AI reuses existing chapter assistant route", () => { assert.match(chapter, /\/assistant/); assert.doesNotMatch(chapter, /new.*AI|create.*AI/i); });
test("30 chapter-only books are queried directly by book", () => { assert.match(workspace, /bookChapter\.findMany/); assert.match(workspace, /bookId: subject\.book\.id/); });
test("31 previous and next navigation follows authorized chapter order", () => { assert.match(workspace, /findIndex/); assert.match(workspace, /previous:/); assert.match(workspace, /next:/); });
test("32 empty optional action types are hidden", () => { assert.match(chapter, /videos\.length > 0/); assert.match(chapter, /chapter\.activities\.length > 0/); });
test("33 all chapter actions use chapter-scoped records", () => { assert.match(workspace, /id: chapterId, bookId:/); assert.match(chapter, /id="read"|id="watch"/); });
test("34 existing assignment and assessment routes are reused", () => { assert.match(chapter, /student-dashboard\/assignments/); assert.match(chapter, /student-dashboard\/assessments/); });
test("35 page loading does not write progress", () => { assert.doesNotMatch(workspace, /studentBookProgress\.(create|update|upsert)|studentRevisionProgress\.(create|update|upsert)/); });
test("36 cross-publisher chapters and resources are constrained", () => { assert.match(workspace, /publisherId: identity\.publisher\.id/); assert.match(workspace, /publisherId: workspace\.identity\.publisher\.id/); });
test("37 inactive and unapproved chapter content is hidden", () => { assert.match(workspace, /approved: true, published: true, archived: false/); });

test("student own-message delete window is limited to fifteen minutes", () => { const now = new Date("2026-08-02T12:00:00Z"); assert.equal(canDeleteOwnSectionMessage({ actorUserId: "u", senderUserId: "u", createdAt: new Date(now.getTime() - 14 * 60_000), now }), true); assert.equal(canDeleteOwnSectionMessage({ actorUserId: "u", senderUserId: "u", createdAt: new Date(now.getTime() - 16 * 60_000), now }), false); });
