import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { canCarryForward, carryForward } from "../lib/student-planner-policy";
import { canPostSectionChat, canReadSectionChat, type SectionChatActor } from "../lib/section-chat-policy";

const read = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const sidebar = read("components/dashboard/Sidebar.tsx"); const header = read("components/dashboard/Header.tsx"); const mobile = read("components/dashboard/TeacherMobileNavigation.tsx"); const tabs = read("components/classroom/ClassTabs.tsx"); const classroom = read("lib/classroom.ts"); const access = read("lib/teacher-dashboard.ts"); const home = read("lib/teacher-experience.ts"); const plan = read("app/teacher-dashboard/classes/[sectionId]/plan/actions.ts"); const studentPlan = read("lib/student-classroom-data.ts"); const assignments = read("lib/assignments/assignment-service.ts") + read("lib/assignments/submission-service.ts"); const assessments = read("app/teacher-dashboard/classes/[sectionId]/assessments/page.tsx") + read("lib/student-assessments.ts"); const materials = read("app/teacher-dashboard/classes/[sectionId]/materials/actions.ts"); const progress = read("lib/classroom.ts"); const chat = read("lib/teacher-class-chat.ts"); const chatSchema = read("prisma/schema.prisma"); const ai = read("app/teacher-dashboard/ai/actions.ts") + read("lib/ai/quota.ts");
const teacher: SectionChatActor = { schoolId: "school", sectionId: "section", active: true, schoolAccessActive: true, role: "TEACHER", officiallyAssigned: true }; const room = { schoolId: "school", sectionId: "section" };

test("1 sidebar contains only the five final items", () => assert.deepEqual([...sidebar.matchAll(/name: "([^"]+)"/g)].map((m) => m[1]), ["Home", "My Classes", "Planner", "Messages", "Resources"]));
test("2 profile is only in avatar menu", () => { assert.doesNotMatch(sidebar, /Profile/); assert.match(header, /teacher-dashboard\/profile/); });
test("3 class workspace uses contextual tabs", () => ["Overview", "Teaching Plan", "Students", "Assignments", "Assessments", "Materials", "Progress", "Class Chat"].forEach((label) => assert.match(tabs, new RegExp(label))));
test("4 mobile navigation uses final navigation", () => { assert.match(mobile, /teacherNavigation\.map/); assert.match(mobile, /grid-cols-5/); });
test("5 classes originate from official assignments", () => { assert.match(classroom, /teacherAssignment\.findMany/); assert.match(classroom, /teacherId: teacher\.id/); });
test("6 cross-school class access is blocked", () => assert.match(classroom, /schoolId: teacher\.schoolId/));
test("7 cross-section access is blocked", () => assert.equal(canReadSectionChat(teacher, { ...room, sectionId: "other" }), false));
test("8 inactive membership is blocked", () => assert.equal(canReadSectionChat({ ...teacher, active: false }, room), false));
test("9 suspended or expired school access is enforced", () => { assert.match(access, /decideSchoolAccess/); assert.match(access, /TEACHER_DASHBOARD/); });
test("10 today classes are teacher scoped", () => { assert.match(home, /sectionIds = classes\.map/); assert.match(home, /sectionId: \{ in: sectionIds \}/); });
test("11 review and grade counts use persisted records", () => { assert.match(home, /assignmentSubmission\.count/); assert.match(home, /assessmentResponse\.count/); });
test("12 recent messages use authorized rooms", () => assert.match(home, /room: \{ schoolId: teacher\.schoolId!, sectionId: \{ in: sectionIds \}/));
test("13 teacher can create a valid plan item", () => assert.match(plan, /academicPlannerItem\.create/));
test("14 unassigned subject planning is denied", () => assert.match(plan, /requireTeacherSubject\(sectionId, sectionSubjectId\)/));
test("15 fixed dates do not shift", () => assert.equal(canCarryForward({ fixedDate: true, status: "NOT_COMPLETED", originalDate: new Date(0), currentDate: new Date(1) }), false));
test("16 movable incomplete items preserve history", () => { const originalDate = new Date(0), currentDate = new Date(1), next = new Date(2); const result = carryForward({ fixedDate: false, status: "NOT_COMPLETED", originalDate, currentDate }, next); assert.equal(result.item.originalDate, originalDate); assert.deepEqual(result.history, { fromDate: currentDate, toDate: next }); });
test("17 student planner reads revised dates", () => assert.match(studentPlan, /date: item\.currentDate/));
test("18 fixed school dates cannot be rescheduled", () => assert.match(plan, /item\.fixedDate/));
test("19 canonical assignment lifecycle remains intact", () => { assert.match(assignments, /ClassroomAssignmentStatus/); assert.doesNotMatch(assignments, /classroomAssignment\.delete/); });
test("20 assigned teacher can create publish and review", () => { assert.match(assignments, /classroomAssignment\.create/); assert.match(assignments, /classroomAssignment\.update/); });
test("21 unauthorized assignment mutation is denied", () => assert.match(assignments, /requireOwnedTeacherAssignment|requireTeacherAssignmentFeature/));
test("22 assignment submission counts remain canonical", () => assert.match(read("lib/assignments/queries.ts"), /summarizeSubmissions/));
test("23 return resubmission and grading remain functional", () => { assert.match(assignments, /RETURNED/); assert.match(assignments, /RESUBMITTED/); assert.match(assignments, /GRADED/); });
test("24 assessments are scoped to selected delivery records", () => assert.match(assessments, /sectionSubjectId: subject\.id|sectionId/));
test("25 assessment attempts require authorized identity", () => assert.match(assessments, /requireStudentAssessment|requireStudent/));
test("26 results publication remains controlled", () => assert.match(assessments, /publishedAt|resultRelease/));
test("27 publisher resources require entitlement", () => assert.match(read("lib/teacher-dashboard.ts"), /resourceScope\.where/));
test("28 teacher materials remain teacher owned", () => assert.match(materials, /teacherId: scope\.teacher\.id/));
test("29 material sharing is section and subject scoped", () => { assert.match(materials, /sectionId/); assert.match(materials, /sectionSubjectId/); });
test("30 material archive is non destructive", () => { assert.match(materials, /archivedAt/); assert.doesNotMatch(materials, /classMaterial\.delete/); });
test("31 progress uses existing analytics and attempts", () => { assert.match(progress, /studentAnalytics/); assert.match(progress, /assessmentAttempt/); });
test("32 progress cannot expose another section", () => assert.match(progress, /sectionId/));
test("33 teacher uses shared section room", () => { assert.match(chat, /sectionChatRoom/); assert.match(chatSchema, /model SectionChatRoom/); });
test("34 authorized teacher can pin announce and moderate", () => { assert.match(chat, /ANNOUNCEMENT/); assert.match(chat, /pinnedAt/); assert.match(chat, /moderateTeacherClassMessage/); });
test("35 students and teachers use the same persisted messages", () => { assert.match(chat, /sectionChatMessage/); assert.match(read("lib/student-class-chat.ts"), /sectionChatMessage/); });
test("36 unassigned teacher cannot read or post", () => { assert.equal(canPostSectionChat({ ...teacher, officiallyAssigned: false }, room), false); assert.match(chat, /requireTeacherClass/); });
test("37 moderation writes audit evidence", () => { assert.match(chat, /writeSecurityAuditEvent/); assert.match(chat, /classroom\.chat\.moderate/); });
test("38 teacher AI respects entitlement and quota", () => { assert.match(ai, /getTeacherAiEntitlement|quota/); assert.match(ai, /requireTeacher/); });
test("39 AI remains grounded to approved assigned content", () => { assert.match(ai, /getBookEntitlementForAuthenticatedUser|bookId/); assert.match(ai, /prepareQuestionPaperDraft|knowledge/i); });
