import SectionSubjectContentManager from "@/components/school/SectionSubjectContentManager";
import { getAcademicClass } from "@/lib/academic";
import { saveSection, setSectionSubjectOrder, toggleSectionSubject } from "../../academic-actions";

export const dynamic = "force-dynamic";
const input = "rounded-xl border px-4 py-3";

export default async function ClassPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { schoolClass, subjects, books, resources } = await getAcademicClass(id);
  const save = saveSection.bind(null, id);
  const toggle = toggleSectionSubject.bind(null, id);
  const order = setSectionSubjectOrder.bind(null, id);

  return <main className="space-y-7 p-4 sm:p-6 lg:p-8">
    <header><p className="font-semibold text-blue-700">{schoolClass.academicYear.name}</p><h1 className="mt-2 text-3xl font-bold">{schoolClass.name}</h1><p className="mt-2 text-slate-600">Manage sections, subjects, teachers, books, and learning resources.</p></header>
    <form action={save} className="grid gap-4 rounded-3xl border bg-white p-6 shadow-sm sm:grid-cols-2 lg:grid-cols-4"><input name="name" required placeholder="Section, for example A" className={input}/><input name="room" placeholder="Room (optional)" className={input}/><input name="capacity" type="number" min="1" placeholder="Capacity" className={input}/><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Add section</button></form>
    {schoolClass.sections.length ? <div className="space-y-5">{schoolClass.sections.map((section) => <article key={section.id} className="rounded-3xl border bg-white p-6 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">{schoolClass.name} · Section {section.name}</h2><p className="mt-2 text-slate-500">{section.room || "Room not set"} · {section.capacity ? `${section.capacity} seats` : "No capacity set"} · {section._count.enrollments} active students</p><p className={`mt-2 text-sm font-semibold ${section.teacherAssignments.some((item) => item.type === "CLASS_TEACHER") ? "text-emerald-700" : "text-amber-700"}`}>Class teacher: {section.teacherAssignments.find((item) => item.type === "CLASS_TEACHER")?.teacher.user.name || "Not assigned"}</p></div><details><summary className="cursor-pointer rounded-xl border px-4 py-2 font-semibold">Edit section</summary><form action={save} className="mt-3 grid gap-3"><input type="hidden" name="id" value={section.id}/><input name="name" defaultValue={section.name} required className={input}/><input name="room" defaultValue={section.room ?? ""} className={input}/><input name="capacity" type="number" min="1" defaultValue={section.capacity ?? ""} className={input}/><label><input name="active" type="checkbox" defaultChecked={section.active}/> Active</label><button className="rounded-xl bg-slate-900 p-3 font-semibold text-white">Save</button></form></details></div>
      <h3 className="mt-7 font-bold">Subjects</h3><div className="mt-3 flex flex-wrap gap-2">{subjects.map((subject) => { const linked = section.subjects.find((item) => item.subjectId === subject.id)?.active ?? false; return <form action={toggle} key={subject.id}><input type="hidden" name="sectionId" value={section.id}/><input type="hidden" name="subjectId" value={subject.id}/><input type="hidden" name="active" value={linked ? "false" : "true"}/><button className={`rounded-full border px-4 py-2 text-sm font-semibold ${linked ? "border-blue-200 bg-blue-50 text-blue-700" : "text-slate-600"}`}>{linked ? "✓ " : "+ "}{subject.name}</button></form>; })}</div>
      {section.subjects.some((item) => item.active) ? <div className="mt-6 space-y-5">{section.subjects.filter((item) => item.active).map((item) => {
        const assignment = section.teacherAssignments.find((candidate) => candidate.subjectId === item.subjectId);
        return <div key={item.id} className="space-y-2"><form action={order} className="flex items-center justify-end gap-2"><input type="hidden" name="sectionSubjectId" value={item.id}/><label className="text-sm text-slate-500">Display order <input aria-label={`${item.subject.name} order`} name="sortOrder" type="number" min="0" defaultValue={item.sortOrder} className="ml-2 w-20 rounded-lg border px-2 py-1"/></label><button className="rounded-lg border bg-white px-3 py-1 text-sm font-semibold">Save</button></form><SectionSubjectContentManager schoolClassId={id} sectionSubjectId={item.id} subjectId={item.subjectId} subjectName={item.subject.name} teacherName={assignment?.teacher.user.name ?? null} books={books.map((book) => ({ id: book.id, title: book.title, coverImage: book.coverImage, subjectId: book.subjectId, className: book.class.name, subjectName: book.subject.name, seriesName: book.series?.name ?? null }))} resources={resources.map((resource) => ({ id: resource.id, title: resource.title, subject: resource.subject, classLevel: resource.classLevel, type: resource.type, audience:resource.audience }))} assignedBookId={item.bookId ?? ""} assignedResourceIds={item.resources.map((resource) => resource.id)}/></div>;
      })}</div> : <p className="mt-5 rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Enable a subject to assign its teacher, book, and resources.</p>}
    </article>)}</div> : <div className="rounded-3xl border bg-white p-12 text-center"><h2 className="text-xl font-bold">No sections yet</h2><p className="mt-2 text-slate-500">Add section A to get started.</p></div>}
  </main>;
}
