import { GapEmpty, GapHero, GapLink } from "@/components/gaps/GapVisuals";
import { getStudentGaps } from "@/lib/gaps/student";
export const dynamic = "force-dynamic"; export const revalidate = 0;
export default async function StudentGapsPage() {
  const report = await getStudentGaps();
  if (report.state !== "READY") return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><GapHero eyebrow="Premium learning support" title="My learning focus" description="Supportive, evidence-based learning signals from your scored activity."/><GapEmpty title={report.state === "LOCKED" ? "Learning Gap Analysis is available with Premium." : "This feature is not available on your platform."} message="Your original learning activity remains available in books, practice, assessments, and reports."/></main>;
  const active = report.gaps.filter((gap) => gap.status === "OPEN" || gap.status === "ACKNOWLEDGED");
  return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><GapHero eyebrow={report.year} title="My learning focus" description="These are learning signals, not diagnoses. They appear only after enough scored evidence and can change as you learn."/>{active.length ? <section className="grid gap-4 lg:grid-cols-2">{active.map((gap) => <article key={gap.id} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><p className="text-sm font-bold text-indigo-700">{gap.subject}</p><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">{gap.severityLabel}</span></div><h2 className="mt-3 text-xl font-bold">{gap.learningArea}</h2><p className="mt-2 text-sm text-slate-600">{gap.message}</p><p className="mt-2 text-xs text-slate-500">Last updated {gap.lastDetectedAt.toLocaleDateString()}</p><div className="mt-5"><GapLink href={`/student-dashboard/gaps/${gap.id}`}>See the evidence</GapLink></div></article>)}</section> : <GapEmpty title={report.sufficientEvidence ? "No learning gaps have been identified yet." : "We need more learning activity before showing an analysis."} message={report.sufficientEvidence ? "This does not imply complete mastery; it only reflects the scored evidence currently available." : "Complete more scored practice or assessments so the analysis has enough evidence."}/>}</main>;
}
