import { CalendarDays } from "lucide-react";
import { getAcademicYears } from "@/lib/academic";
import { saveAcademicYear, setCurrentAcademicYear } from "../academic-actions";

export const dynamic = "force-dynamic";
const input = "w-full rounded-xl border px-4 py-3";

export default async function AcademicYearsPage() {
  const years = await getAcademicYears();
  const current = years.find((year) => year.current);

  return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><header><h1 className="text-3xl font-bold">Academic Years</h1><p className="mt-2 text-slate-600">Set up each school year and choose the one staff should use now.</p></header>
    {current ? <section className="rounded-2xl bg-blue-50 p-5"><p className="text-sm font-bold uppercase tracking-wide text-blue-700">Current academic year</p><p className="mt-1 text-2xl font-bold text-blue-950">{current.name}</p><p className="mt-1 text-sm text-blue-800">{current.startDate.toLocaleDateString("en-IN")} – {current.endDate.toLocaleDateString("en-IN")}</p></section> : <p className="rounded-2xl border border-amber-200 bg-amber-50 p-5 font-semibold text-amber-900">No current academic year is selected.</p>}
    <form action={saveAcademicYear} className="grid gap-4 rounded-3xl border bg-white p-6 shadow-sm md:grid-cols-2 xl:grid-cols-5"><input name="name" required placeholder="2026-27" className={input}/><input aria-label="Start date" name="startDate" type="date" required className={input}/><input aria-label="End date" name="endDate" type="date" required className={input}/><label className="flex items-center gap-3 rounded-xl border px-4"><input name="current" type="checkbox"/> Use this year now</label><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Add academic year</button></form>
    {years.length ? <div className="grid gap-5 lg:grid-cols-2">{years.map((year) => <article key={year.id} className={`rounded-3xl border bg-white p-6 shadow-sm ${!year.active ? "opacity-75" : ""}`}><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">{year.name}</h2><p className="mt-2 text-slate-500">{year.startDate.toLocaleDateString("en-IN")} – {year.endDate.toLocaleDateString("en-IN")}</p></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${year.current ? "bg-green-100 text-green-700" : year.active ? "bg-blue-50 text-blue-700" : "bg-slate-100 text-slate-600"}`}>{year.current ? "Current" : year.active ? "Active" : "Archived"}</span></div><p className="mt-5 text-sm text-slate-600">{year._count.classes} classes · {year._count.enrollments} student enrolments</p><div className="mt-5 flex flex-wrap gap-3">{!year.current && year.active ? <form action={setCurrentAcademicYear}><input type="hidden" name="id" value={year.id}/><button className="rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white">Make current</button></form> : null}<details><summary className="cursor-pointer rounded-xl border px-4 py-2 font-semibold">Edit year</summary><form action={saveAcademicYear} className="mt-4 grid gap-3"><input type="hidden" name="id" value={year.id}/><input name="name" defaultValue={year.name} required className={input}/><input name="startDate" type="date" defaultValue={year.startDate.toISOString().slice(0, 10)} required className={input}/><input name="endDate" type="date" defaultValue={year.endDate.toISOString().slice(0, 10)} required className={input}/><label><input name="active" type="checkbox" defaultChecked={year.active}/> Active</label><label><input name="current" type="checkbox" defaultChecked={year.current}/> Current</label><button className="rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white">Save changes</button></form></details></div></article>)}</div> : <div className="rounded-3xl border bg-white p-14 text-center"><CalendarDays className="mx-auto h-12 w-12 text-slate-300"/><h2 className="mt-4 text-xl font-bold">Add your first academic year</h2><p className="mt-2 text-slate-500">Classes, sections, enrolments, and assignments all use this context.</p></div>}
  </main>;
}
