"use server";

import { AcademicPlannerItemStatus } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { requireTeacherSubject } from "@/lib/teacher-experience";

export async function createTeachingPlanAction(formData: FormData) { const sectionId = String(formData.get("sectionId") ?? ""); const sectionSubjectId = String(formData.get("sectionSubjectId") ?? ""); const { scope, subject } = await requireTeacherSubject(sectionId, sectionSubjectId); const title = String(formData.get("title") ?? "").trim(); const date = new Date(String(formData.get("date") ?? "")); if (!title || title.length > 180 || Number.isNaN(date.getTime())) throw new Error("Enter a valid plan title and date."); await prisma.academicPlannerItem.create({ data: { schoolId: scope.schoolId, academicYearId: scope.academicYear.id, sectionId, sectionSubjectId: subject.id, type: "TEACHING", title, description: String(formData.get("description") ?? "").trim() || null, fixedDate: formData.get("fixedDate") === "on", originalDate: date, currentDate: date, status: "PLANNED" } }); revalidatePath(`/teacher-dashboard/classes/${sectionId}/plan`); revalidatePath("/teacher-dashboard/planner"); }

export async function updateTeachingPlanStatusAction(formData: FormData) { const sectionId = String(formData.get("sectionId") ?? ""); const sectionSubjectId = String(formData.get("sectionSubjectId") ?? ""); await requireTeacherSubject(sectionId, sectionSubjectId); const id = String(formData.get("id") ?? ""); const status = String(formData.get("status") ?? "") as AcademicPlannerItemStatus; if (!["IN_PROGRESS", "COMPLETED", "NOT_COMPLETED", "SKIPPED"].includes(status)) throw new Error("Invalid status."); const item = await prisma.academicPlannerItem.findFirst({ where: { id, sectionId, sectionSubjectId } }); if (!item) throw new Error("Plan item not found."); await prisma.academicPlannerItem.update({ where: { id }, data: { status, completedAt: status === "COMPLETED" ? new Date() : null } }); revalidatePath(`/teacher-dashboard/classes/${sectionId}/plan`); revalidatePath("/teacher-dashboard/planner"); }

export async function rescheduleTeachingPlanAction(formData: FormData) { const sectionId = String(formData.get("sectionId") ?? ""); const sectionSubjectId = String(formData.get("sectionSubjectId") ?? ""); const { scope } = await requireTeacherSubject(sectionId, sectionSubjectId); const id = String(formData.get("id") ?? ""); const date = new Date(String(formData.get("date") ?? "")); const reason = String(formData.get("reason") ?? "").trim(); const item = await prisma.academicPlannerItem.findFirst({ where: { id, sectionId, sectionSubjectId } }); if (!item || item.fixedDate || Number.isNaN(date.getTime()) || !reason) throw new Error("This item cannot be rescheduled."); await prisma.$transaction(async (tx) => { await tx.academicPlannerItem.update({ where: { id }, data: { currentDate: date, status: "RESCHEDULED" } }); await tx.academicPlannerReschedule.create({ data: { plannerItemId: id, fromDate: item.currentDate, toDate: date, reason, createdByUserId: scope.teacher.userId } }); }); revalidatePath(`/teacher-dashboard/classes/${sectionId}/plan`); revalidatePath("/teacher-dashboard/planner"); }
