import "server-only";

import { SecurityAuditOutcome, UserRole } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { getTeacherClasses, requireTeacherClass } from "@/lib/classroom";
import { writeSecurityAuditEvent } from "@/lib/security-audit";
import { requireTeacher } from "@/lib/teacher-dashboard";

async function scope(sectionId: string) { const classroom = await requireTeacherClass(sectionId); const room = await prisma.sectionChatRoom.upsert({ where: { sectionId }, update: {}, create: { schoolId: classroom.schoolId, academicYearId: classroom.academicYear.id, sectionId } }); if (room.schoolId !== classroom.schoolId || room.academicYearId !== classroom.academicYear.id) throw new Error("Chat scope is invalid."); return { classroom, room }; }

export async function listTeacherClassChat(sectionId: string, cursor?: string | null) { const { classroom, room } = await scope(sectionId); const read = await prisma.sectionChatReadState.findUnique({ where: { roomId_userId: { roomId: room.id, userId: classroom.teacher.userId } } }); const messages = await prisma.sectionChatMessage.findMany({ where: { roomId: room.id, deletedAt: null }, take: 51, ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}), orderBy: [{ createdAt: "desc" }, { id: "desc" }], include: { sender: { select: { name: true, role: true } }, replyTo: { select: { id: true, text: true, sender: { select: { name: true } } } } } }); const hasMore = messages.length > 50; if (hasMore) messages.pop(); const unread = await prisma.sectionChatMessage.count({ where: { roomId: room.id, deletedAt: null, senderUserId: { not: classroom.teacher.userId }, createdAt: { gt: read?.lastReadAt ?? new Date(0) } } }); await prisma.sectionChatReadState.upsert({ where: { roomId_userId: { roomId: room.id, userId: classroom.teacher.userId } }, update: { lastReadAt: new Date() }, create: { roomId: room.id, userId: classroom.teacher.userId } }); return { messages: messages.reverse(), unread, nextCursor: hasMore ? messages[0]?.id ?? null : null, currentUserId: classroom.teacher.userId }; }

export async function sendTeacherClassMessage(sectionId: string, input: { text: string; replyToId?: string | null; announcement?: boolean }) { const { classroom, room } = await scope(sectionId); const text = input.text.trim(); if (!text || text.length > 2000) throw new Error("Message must contain between 1 and 2,000 characters."); if (input.replyToId && !(await prisma.sectionChatMessage.findFirst({ where: { id: input.replyToId, roomId: room.id, deletedAt: null } }))) throw new Error("Reply target is unavailable."); return prisma.sectionChatMessage.create({ data: { roomId: room.id, senderUserId: classroom.teacher.userId, text, replyToId: input.replyToId || null, kind: input.announcement ? "ANNOUNCEMENT" : "MESSAGE" } }); }

export async function pinTeacherClassMessage(sectionId: string, messageId: string, pinned: boolean) { const { classroom, room } = await scope(sectionId); const message = await prisma.sectionChatMessage.findFirst({ where: { id: messageId, roomId: room.id, deletedAt: null } }); if (!message) throw new Error("Message not found."); return prisma.$transaction(async (tx) => { const updated = await tx.sectionChatMessage.update({ where: { id: message.id }, data: { pinnedAt: pinned ? new Date() : null, pinnedByUserId: pinned ? classroom.teacher.userId : null } }); await writeSecurityAuditEvent(tx, { actor: { userId: classroom.teacher.userId, role: UserRole.TEACHER, publisherId: classroom.publisherId }, action: "classroom.chat.pin", targetType: "SectionChatMessage", targetId: message.id, outcome: SecurityAuditOutcome.SUCCESS, metadata: { pinned } }); return updated; }); }

export async function moderateTeacherClassMessage(sectionId: string, messageId: string, reason: string) { const { classroom, room } = await scope(sectionId); const message = await prisma.sectionChatMessage.findFirst({ where: { id: messageId, roomId: room.id, deletedAt: null } }); if (!message || message.senderUserId === classroom.teacher.userId) throw new Error("Message cannot be moderated."); const safeReason = reason.trim().slice(0, 300); if (!safeReason) throw new Error("A moderation reason is required."); await prisma.$transaction(async (tx) => { await tx.sectionChatMessage.update({ where: { id: message.id }, data: { deletedAt: new Date() } }); await writeSecurityAuditEvent(tx, { actor: { userId: classroom.teacher.userId, role: UserRole.TEACHER, publisherId: classroom.publisherId }, action: "classroom.chat.moderate", targetType: "SectionChatMessage", targetId: message.id, outcome: SecurityAuditOutcome.SUCCESS, metadata: { sectionId, reason: safeReason, senderUserId: message.senderUserId } }); }); }

export async function getTeacherMessageRooms() { const teacher = await requireTeacher(); const classes = await getTeacherClasses(); await Promise.all(classes.map((item) => prisma.sectionChatRoom.upsert({ where: { sectionId: item.sectionId }, update: {}, create: { schoolId: teacher.schoolId!, academicYearId: item.academicYearId, sectionId: item.sectionId } }))); const rooms = await prisma.sectionChatRoom.findMany({ where: { schoolId: teacher.schoolId!, sectionId: { in: classes.map((item) => item.sectionId) } }, include: { section: { include: { schoolClass: true } }, messages: { where: { deletedAt: null }, orderBy: { createdAt: "desc" }, take: 1, include: { sender: { select: { name: true } } } }, readStates: { where: { userId: teacher.userId }, take: 1 } }, orderBy: { updatedAt: "desc" } }); return Promise.all(rooms.map(async (room) => ({ ...room, unread: await prisma.sectionChatMessage.count({ where: { roomId: room.id, deletedAt: null, senderUserId: { not: teacher.userId }, createdAt: { gt: room.readStates[0]?.lastReadAt ?? new Date(0) } } }) }))); }
