import{AiUsageStatus,TeacherAiPlan,Prisma}from"@prisma/client";import{prisma}from"@/lib/prisma";
const PREMIUM_LIMIT=5,RESERVATION_MINUTES=10,IST_OFFSET_MS=330*60*1000;
export function getIstDayBounds(now=new Date()){const shifted=new Date(now.getTime()+IST_OFFSET_MS);const startShifted=Date.UTC(shifted.getUTCFullYear(),shifted.getUTCMonth(),shifted.getUTCDate());return{start:new Date(startShifted-IST_OFFSET_MS),end:new Date(startShifted+86400000-IST_OFFSET_MS),resetAt:new Date(startShifted+86400000-IST_OFFSET_MS),timezone:"Asia/Kolkata" as const}}
export async function getDailyAiUsage(teacherId:string,now=new Date()){const{start,end,resetAt,timezone}=getIstDayBounds(now);const consumed=await prisma.aiUsage.count({where:{teacherId,status:AiUsageStatus.CONSUMED,consumedAt:{gte:start,lt:end}}});return{consumed,resetAt,timezone,start,end}}
export async function getTeacherAiEntitlement(teacherId:string,now=new Date()){const teacher=await prisma.teacher.findUnique({where:{id:teacherId},select:{aiPlan:true,aiDailyLimit:true,aiPlanExpiresAt:true}});if(!teacher)throw new Error("Teacher not found.");const expired=Boolean(teacher.aiPlanExpiresAt&&teacher.aiPlanExpiresAt<=now),plan=expired?TeacherAiPlan.STANDARD:teacher.aiPlan,limit=plan===TeacherAiPlan.PREMIUM?(teacher.aiDailyLimit>0?teacher.aiDailyLimit:PREMIUM_LIMIT):0,usage=await getDailyAiUsage(teacherId,now);return{plan,limit,used:usage.consumed,remaining:Math.max(0,limit-usage.consumed),resetAt:usage.resetAt,timezone:usage.timezone,expiresAt:teacher.aiPlanExpiresAt,canGenerate:plan===TeacherAiPlan.PREMIUM&&usage.consumed<limit,message:plan!==TeacherAiPlan.PREMIUM?"AI generation requires Premium access.":usage.consumed>=limit?`You have used all ${limit} AI generations for today.`:null}}
export async function assertCanGenerate(teacherId:string){const entitlement=await getTeacherAiEntitlement(teacherId);if(!entitlement.canGenerate)throw new Error(entitlement.message??"AI generation is unavailable.");return entitlement}
export async function reserveQuota(input:{teacherId:string;generationId:string;tool:string}){return prisma.$transaction(async tx=>{await lockTeacher(tx,input.teacherId);const now=new Date(),bounds=getIstDayBounds(now);await tx.aiUsage.updateMany({where:{teacherId:input.teacherId,status:AiUsageStatus.RESERVED,expiresAt:{lte:now}},data:{status:AiUsageStatus.RELEASED,releasedAt:now}});const teacher=await tx.teacher.findUnique({where:{id:input.teacherId},select:{aiPlan:true,aiDailyLimit:true,aiPlanExpiresAt:true}});if(!teacher)throw new Error("Teacher not found.");const premium=teacher.aiPlan===TeacherAiPlan.PREMIUM&&(!teacher.aiPlanExpiresAt||teacher.aiPlanExpiresAt>now);if(!premium)throw new Error("AI generation requires Premium access.");const limit=teacher.aiDailyLimit>0?teacher.aiDailyLimit:PREMIUM_LIMIT;const occupied=await tx.aiUsage.count({where:{teacherId:input.teacherId,OR:[{status:AiUsageStatus.CONSUMED,consumedAt:{gte:bounds.start,lt:bounds.end}},{status:AiUsageStatus.RESERVED,expiresAt:{gt:now}}]}});if(occupied>=limit)throw new Error(`You have used or reserved all ${limit} AI generations for today.`);return tx.aiUsage.create({data:{teacherId:input.teacherId,generationId:input.generationId,tool:input.tool,status:AiUsageStatus.RESERVED,expiresAt:new Date(now.getTime()+RESERVATION_MINUTES*60000)}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function consumeQuota(input:{teacherId:string;generationId:string}){return prisma.$transaction(async tx=>{await lockTeacher(tx,input.teacherId);const now=new Date(),usage=await tx.aiUsage.findUnique({where:{generationId:input.generationId}});if(!usage||usage.teacherId!==input.teacherId)throw new Error("Quota reservation not found.");if(usage.status===AiUsageStatus.CONSUMED)return usage;if(usage.status!==AiUsageStatus.RESERVED||usage.expiresAt<=now)throw new Error("Quota reservation expired or was released.");const updated=await tx.aiUsage.update({where:{id:usage.id},data:{status:AiUsageStatus.CONSUMED,consumedAt:now}});await tx.aiGeneration.update({where:{id:input.generationId},data:{providerCalled:true,quotaConsumed:true,completedAt:now,failureReason:null,status:"COMPLETED"}});return updated},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
export async function releaseQuota(input:{teacherId:string;generationId:string;failureReason?:string}){return prisma.$transaction(async tx=>{await lockTeacher(tx,input.teacherId);const now=new Date();await tx.aiUsage.updateMany({where:{teacherId:input.teacherId,generationId:input.generationId,status:AiUsageStatus.RESERVED},data:{status:AiUsageStatus.RELEASED,releasedAt:now}});await tx.aiGeneration.updateMany({where:{id:input.generationId,teacherId:input.teacherId},data:{quotaConsumed:false,failureReason:input.failureReason?.slice(0,500)??null}})},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}
async function lockTeacher(tx:Prisma.TransactionClient,teacherId:string){await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtext(${teacherId}))`}
