import Link from "next/link";
import { getSchoolMentor } from "@/lib/school-mentors";
import { assignSchoolMentorStudentAction, removeSchoolMentorStudentAction, resendSchoolMentorActivationAction, setSchoolMentorActiveAction } from "../actions";

const button = "rounded-xl border px-4 py-2 text-sm font-bold";

export default async function SchoolMentorDetailPage({ params, searchParams }: { params: Promise<{ mentorId: string }>; searchParams: Promise<{ message?: string }> }) {
  const [{ mentorId }, query] = await Promise.all([params, searchParams]);
  const detail = await getSchoolMentor(mentorId);
  const user = detail.membership.user;
  return <main className="space-y-6 p-4 sm:p-6 lg:p-8"><header><Link href="/school-dashboard/people/mentors" className="font-semibold text-blue-700">← Back to Mentors</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">{user.name}</h1><p className="mt-2 text-slate-600">{detail.mentor.specialty||"School Mentor"} · {user.email}</p></div><span className={`rounded-full px-4 py-2 text-sm font-bold ${detail.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{detail.active?"Active":"Inactive"}</span></div></header>
    {query.message?<p role="status" className="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-blue-900">{query.message}</p>:null}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Account status",detail.accountStatus],["Login readiness",detail.loginReady?"Ready":"Not ready"],["Phone",user.phone||"Not provided"],["Assigned students",String(detail.mentor.assignments.length)]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 font-bold">{value}</p></div>)}</section>
    {!detail.loginReady?<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><h2 className="font-bold">Login is not ready</h2><p className="mt-2 text-sm">Required: completed account activation, active mentor membership, Mentor Platform enabled, paid active school access, and at least one active eligible student assignment.</p></section>:null}
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Account and access</h2><dl className="mt-5 grid gap-3 text-sm"><div><dt className="text-slate-500">Email</dt><dd className="font-semibold">{user.email}</dd></div><div><dt className="text-slate-500">Designation</dt><dd className="font-semibold">{detail.mentor.specialty||"School Mentor"}</dd></div><div><dt className="text-slate-500">Account</dt><dd className="font-semibold">{detail.accountStatus}</dd></div></dl><div className="mt-6 flex flex-wrap gap-3">{detail.accountStatus==="Activation pending"?<form action={resendSchoolMentorActivationAction.bind(null,mentorId)}><button className={button}>Resend activation</button></form>:null}<form action={setSchoolMentorActiveAction.bind(null,mentorId)}><input type="hidden" name="active" value={detail.active?"false":"true"}/><button className={`${button} ${detail.active?"border-rose-200 text-rose-700":"border-emerald-200 text-emerald-700"}`}>{detail.active?"Deactivate Mentor":"Activate Mentor"}</button></form></div></div>
      <div className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Assign Student</h2><p className="mt-2 text-sm text-slate-600">Only active students in this school with a current eligible Mentor plan can be assigned.</p>{detail.candidateStudents.length?<form action={assignSchoolMentorStudentAction.bind(null,mentorId)} className="mt-5 space-y-4"><select name="studentId" required className="w-full rounded-xl border px-4 py-3" defaultValue=""><option value="" disabled>Select a student</option>{detail.candidateStudents.map((student)=>{const enrollment=student.enrollments[0];return <option key={student.id} value={student.id}>{student.name} · {student.admissionNumber}{enrollment?` · ${enrollment.schoolClass.name}-${enrollment.section.name}`:""}</option>})}</select><button disabled={!detail.active} className="w-full rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-50">Assign Student</button></form>:<p className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm text-slate-600">No unassigned active students are available.</p>}</div></section>
    <section className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Assigned Students</h2>{detail.mentor.assignments.length?<div className="mt-5 divide-y">{detail.mentor.assignments.map((assignment)=>{const enrollment=assignment.student.enrollments[0];return <div key={assignment.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="font-bold">{assignment.student.name}</p><p className="mt-1 text-sm text-slate-500">{assignment.student.admissionNumber}{enrollment?` · ${enrollment.schoolClass.name}-${enrollment.section.name}`:""} · {assignment.academicYear.name}</p></div><form action={removeSchoolMentorStudentAction.bind(null,mentorId,assignment.id)}><button className={`${button} border-rose-200 text-rose-700`}>Remove Student</button></form></div>})}</div>:<p className="mt-5 rounded-2xl bg-slate-50 p-8 text-center text-sm text-slate-600">No students are assigned to this mentor.</p>}</section>
  </main>;
}
