import Link from "next/link";
import { GraduationCap, UserRoundCheck, Users } from "lucide-react";
import { getStudents } from "@/lib/academic";
import { getSchoolParents, getSchoolStaff, getSchoolTeachers } from "@/lib/school-dashboard";
import { getSchoolFeatureAccess } from "@/lib/school-feature-access";

export const dynamic = "force-dynamic";
const tabs = ["students", "teachers", "parents", "staff"] as const;

export default async function PeoplePage({ searchParams }: { searchParams: Promise<{ tab?: string }> }) {
  const params = await searchParams;
  const tab = tabs.includes(params.tab as typeof tabs[number]) ? params.tab as typeof tabs[number] : "students";
  const [parentAccess, mentorAccess] = await Promise.all([getSchoolFeatureAccess("PARENT_PORTAL"), getSchoolFeatureAccess("MENTOR_PORTAL")]);
  const [studentData, teachers, staffData] = await Promise.all([getStudents({}), getSchoolTeachers(), getSchoolStaff()]);
  const parents = parentAccess.allowed ? await getSchoolParents() : [];
  return <main className="space-y-5 p-4 text-[15px] sm:p-6 lg:p-8">
    <header><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">People</p><h1 className="mt-1 text-2xl font-bold text-slate-950">People</h1><p className="mt-1 text-sm text-slate-600">Manage the people connected to your school from compact lists.</p></header>
    <nav className="flex flex-wrap gap-1 rounded-xl border border-slate-200 bg-white p-2 shadow-sm">{tabs.filter((item) => item !== "parents" || parentAccess.allowed).map((item) => <Link key={item} href={"/school-dashboard/people?tab=" + item} className={"rounded-lg px-3 py-2 text-sm font-semibold capitalize " + (tab === item ? "bg-blue-700 text-white" : "text-slate-600 hover:bg-slate-50")}>{item}</Link>)}{mentorAccess.allowed ? <Link href="/school-dashboard/people/mentors" className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">Mentors</Link> : null}<Link href="/school-dashboard/teacher-requests" className="rounded-lg px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">Requests</Link></nav>
    {tab === "students" ? <CompactList title="Students" count={studentData.students.length} icon={GraduationCap} action="Add student" href="/school-dashboard/students"><div className="grid grid-cols-[minmax(12rem,2fr)_minmax(8rem,1fr)_minmax(8rem,1fr)_auto] gap-3 px-4 py-2 text-xs font-bold uppercase tracking-wide text-slate-500"><span>Name</span><span>Identifier</span><span>Class / section</span><span>Status</span></div>{studentData.students.map((item) => <Row key={item.id} href={"/school-dashboard/students/" + item.id} name={item.displayName || item.name} identifier={item.admissionNumber} detail={item.enrollments[0] ? item.enrollments[0].schoolClass.name + " · " + item.enrollments[0].section.name : "Not enrolled"} active={item.active}/>)}</CompactList> : null}
    {tab === "teachers" ? <CompactList title="Teachers" count={teachers.length} icon={UserRoundCheck} action="Add teacher" href="/school-dashboard/teachers"><div className="grid grid-cols-[minmax(12rem,2fr)_minmax(12rem,1.5fr)_minmax(8rem,1fr)_auto] gap-3 px-4 py-2 text-xs font-bold uppercase tracking-wide text-slate-500"><span>Name</span><span>Email</span><span>Assignments</span><span>Status</span></div>{teachers.map((item) => <Row key={item.id} href={"/school-dashboard/teachers?query=" + encodeURIComponent(item.user.name)} name={item.user.name} identifier={item.user.email} detail={item.assignments.length + " active assignments"} active={item.active}/>)}</CompactList> : null}
    {tab === "parents" ? <CompactList title="Parents" count={parents.length} icon={Users} action="Manage students" href="/school-dashboard/students"><div className="grid grid-cols-[minmax(12rem,2fr)_minmax(12rem,1.5fr)_minmax(8rem,1fr)_auto] gap-3 px-4 py-2 text-xs font-bold uppercase tracking-wide text-slate-500"><span>Name</span><span>Email</span><span>Linked students</span><span>Status</span></div>{parents.map((item) => <Row key={item.id} href="/school-dashboard/students" name={item.user.name} identifier={item.user.email} detail={item.relationships.map((relationship) => relationship.student.name).join(", ") || "No linked student"} active={item.active}/>)}</CompactList> : null}
    {tab === "staff" ? <CompactList title="Staff" count={staffData.memberships.length} icon={Users} action="Manage staff" href="/school-dashboard/staff"><div className="grid grid-cols-[minmax(12rem,2fr)_minmax(12rem,1.5fr)_minmax(8rem,1fr)_auto] gap-3 px-4 py-2 text-xs font-bold uppercase tracking-wide text-slate-500"><span>Name</span><span>Email</span><span>Role</span><span>Status</span></div>{staffData.memberships.map((item) => <Row key={item.id} href="/school-dashboard/staff" name={item.userName} identifier={item.userEmail} detail={item.role.replaceAll("_", " ")} active={item.active}/>)}</CompactList> : null}
  </main>;
}

function CompactList({ title, count, icon: Icon, action, href, children }: { title: string; count: number; icon: typeof Users; action: string; href: string; children: React.ReactNode }) {
  return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-4 py-3"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-blue-700"/><h2 className="font-bold text-slate-950">{title}</h2><span className="text-xs text-slate-500">{count}</span></div><Link href={href} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white">+ {action}</Link></div>{count ? <div className="divide-y divide-slate-100">{children}</div> : <p className="px-4 py-10 text-center text-sm text-slate-500">No {title.toLowerCase()} found.</p>}</section>;
}

function Row({ href, name, identifier, detail, active }: { href: string; name: string; identifier: string | null; detail: string; active: boolean }) {
  return <Link href={href} className="grid grid-cols-[minmax(12rem,2fr)_minmax(8rem,1fr)_minmax(8rem,1fr)_auto] items-center gap-3 px-4 py-3 text-sm hover:bg-slate-50"><span className="font-semibold text-slate-900">{name}</span><span className="truncate text-slate-600">{identifier ?? "Not provided"}</span><span className="truncate text-slate-600">{detail}</span><span className={"rounded-full px-2 py-1 text-xs font-bold " + (active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600")}>{active ? "Active" : "Inactive"}</span></Link>;
}
