import Link from "next/link";
import { GraduationCap, UserRoundCheck, Users } from "lucide-react";
import { getStudents } from "@/lib/academic";
import { getSchoolParents, getSchoolStaff, getSchoolTeachers } from "@/lib/school-dashboard";
export const dynamic = "force-dynamic";
const tabs = ["students","teachers","parents","staff"] as const;
export default async function PeoplePage({searchParams}:{searchParams:Promise<{tab?:string}>}) {
  const params=await searchParams; const tab=tabs.includes(params.tab as typeof tabs[number])?params.tab as typeof tabs[number]:"students";
  const [studentData,teachers,parents,staffData]=await Promise.all([getStudents({}),getSchoolTeachers(),getSchoolParents(),getSchoolStaff()]);
  return <main className="space-y-6 p-4 sm:p-6 lg:p-8"><header><h1 className="text-3xl font-bold">People</h1><p className="mt-2 text-slate-500">One place for the students, teachers, parents, and staff connected to your school.</p></header><nav className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2">{tabs.map(item=><Link key={item} href={`/school-dashboard/people?tab=${item}`} className={`rounded-xl px-5 py-3 text-sm font-semibold capitalize ${tab===item?"bg-blue-600 text-white":"hover:bg-slate-50"}`}>{item}</Link>)}</nav>
  {tab==="students"&&<Directory title="Students" count={studentData.students.length} icon={GraduationCap} action="Manage students" href="/school-dashboard/students">{studentData.students.map(item=><Row key={item.id} name={item.displayName||item.name} meta={`${item.admissionNumber} · ${item.enrollments[0] ? `${item.enrollments[0].schoolClass.name}-${item.enrollments[0].section.name}` : "Not enrolled"}`} status={item.active?"Active":"Inactive"}/>)}</Directory>}
  {tab==="teachers"&&<Directory title="Teachers" count={teachers.length} icon={UserRoundCheck} action="Manage teachers" href="/school-dashboard/teachers">{teachers.map(item=><Row key={item.id} name={item.user.name} meta={`${item.user.email} · ${item.assignments.length} active assignments`} status={item.active?"Active":"Inactive"}/>)}</Directory>}
  {tab==="parents"&&<Directory title="Parents" count={parents.length} icon={Users} action="Manage through students" href="/school-dashboard/students">{parents.map(item=><Row key={item.id} name={item.user.name} meta={`${item.user.email} · ${item.relationships.map(r=>r.student.name).join(", ")||"No linked student"}`} status={item.active?"Active":"Inactive"}/>)}</Directory>}
  {tab==="staff"&&<Directory title="Staff" count={staffData.memberships.length} icon={Users} action="Manage staff" href="/school-dashboard/staff">{staffData.memberships.map(item=><Row key={item.id} name={item.userName} meta={`${item.userEmail} · ${item.role.replaceAll("_"," ")}`} status={item.active?"Active":"Inactive"}/>)}</Directory>}
  </main>;
}
function Directory({title,count,icon:Icon,action,href,children}:{title:string;count:number;icon:typeof Users;action:string;href:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon/></span><div><h2 className="font-bold">{title}</h2><p className="text-xs text-slate-500">{count} records</p></div></div><Link href={href} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">{action}</Link></div><div className="mt-5 divide-y">{count?children:<p className="py-10 text-center text-sm text-slate-500">No {title.toLowerCase()} found.</p>}</div></section>}
function Row({name,meta,status}:{name:string;meta:string;status:string}){return <div className="flex items-center justify-between gap-4 py-4"><div className="min-w-0"><strong className="block truncate text-sm">{name}</strong><p className="mt-1 truncate text-xs text-slate-500">{meta}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${status==="Active"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{status}</span></div>}
