import Link from "next/link";
import { Search } from "lucide-react";
import { getSchoolTeachers } from "@/lib/school-dashboard";
import { createSchoolTeacher, setSchoolTeacherActive, updateSchoolTeacher } from "../school-actions";

export const dynamic = "force-dynamic";
export const revalidate = 0;
const input = "h-9 w-full rounded-lg border border-slate-300 px-3 text-sm";

export default async function SchoolTeachersPage({ searchParams }: { searchParams: Promise<{ query?: string }> }) {
  const { query } = await searchParams;
  const teachers = await getSchoolTeachers(query?.trim());
  return <main className="space-y-5 p-4 text-[15px] sm:p-6 lg:p-8">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">People</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Teachers</h1><p className="mt-1 text-sm text-slate-600">Accounts receive classroom visibility only through Teacher Assignments.</p></div><div className="flex flex-wrap gap-2"><Link href="/school-dashboard/teachers/bulk-upload" className="rounded-lg border border-blue-200 bg-white px-4 py-2 text-sm font-bold text-blue-700">Bulk Upload</Link><a href="#add-teacher" className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white">+ Add teacher</a></div></header>
    <details id="add-teacher" className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><summary className="cursor-pointer text-sm font-bold text-blue-700">Create a school teacher account</summary><form action={createSchoolTeacher} className="mt-3 grid gap-3 md:grid-cols-4"><input name="name" required placeholder="Name" className={input}/><input name="email" type="email" required placeholder="Email" className={input}/><input name="phone" placeholder="Mobile (optional)" className={input}/><input name="designation" placeholder="Designation" className={input}/><button className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white md:col-start-4">Create and invite</button></form><p className="mt-2 text-xs text-slate-500">Activation is sent through the existing secure password workflow.</p></details>
    <form className="flex gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><Search className="mt-2 h-4 w-4 text-slate-400"/><input name="query" defaultValue={query} placeholder="Search name, email, subject, or class" className="h-9 flex-1 rounded-lg border border-slate-300 px-3 text-sm"/><button className="rounded-lg bg-slate-900 px-3 text-sm font-bold text-white">Search</button></form>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{teachers.length ? <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-2.5">Name</th><th className="px-4 py-2.5">Email</th><th className="px-4 py-2.5">Assignments</th><th className="px-4 py-2.5">Status</th><th className="px-4 py-2.5">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{teachers.map((teacher) => <tr key={teacher.id}><td className="px-4 py-3 font-semibold">{teacher.user.name}<span className="block text-xs font-normal text-slate-500">{teacher.designation}</span></td><td className="px-4 py-3 text-slate-600">{teacher.user.email}</td><td className="max-w-[280px] px-4 py-3 text-xs text-slate-600">{teacher.assignments.length ? teacher.assignments.map((item) => (item.subject?.name ?? "Class teacher") + " · " + item.schoolClass.name + " " + item.section.name).join(", ") : "No active assignments"}</td><td className="px-4 py-3"><span className={"rounded-full px-2 py-1 text-xs font-bold " + (teacher.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600")}>{teacher.active ? "Active" : "Inactive"}</span></td><td className="px-4 py-3"><details><summary className="cursor-pointer font-bold text-blue-700">Edit</summary><form action={updateSchoolTeacher.bind(null, teacher.id)} className="mt-2 grid gap-2 rounded-lg border bg-slate-50 p-2"><input name="name" required defaultValue={teacher.user.name} className={input}/><input name="email" type="email" required defaultValue={teacher.user.email} className={input}/><input name="phone" defaultValue={teacher.user.phone ?? ""} placeholder="Mobile" className={input}/><input name="designation" defaultValue={teacher.designation} className={input}/><button className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Save</button></form><form action={setSchoolTeacherActive} className="mt-2"><input type="hidden" name="teacherId" value={teacher.id}/><input type="hidden" name="active" value={teacher.active ? "false" : "true"}/><button className="text-xs font-bold text-rose-700">{teacher.active ? "Deactivate" : "Reactivate"}</button></form></details></td></tr>)}</tbody></table></div> : <p className="px-4 py-10 text-center text-sm text-slate-500">No teachers found.</p>}</section>
  </main>;
}
