import Link from "next/link";
import { CalendarDays, ChartNoAxesCombined, NotebookPen, ScanSearch, UsersRound } from "lucide-react";
import { getMentorDashboard } from "@/lib/mentor-dashboard";

export default async function MentorDashboardPage() {
  const report = await getMentorDashboard();
  const cards = [
    { label: "Assigned students", value: report.assignments.length, icon: UsersRound },
    { label: "Open gaps", value: report.openGaps, icon: ScanSearch },
    { label: "Active remedials", value: report.activeRemedials, icon: ChartNoAxesCombined },
    { label: "Upcoming sessions", value: report.upcomingSessions.length, icon: CalendarDays },
    { label: "Unread notes", value: report.unreadNotes, icon: NotebookPen },
  ];
  return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><header className="rounded-3xl bg-gradient-to-br from-indigo-800 to-blue-600 p-8 text-white"><p className="font-bold text-white/75">Mentor workspace</p><h1 className="mt-2 text-3xl font-bold">Guide assigned learners</h1><p className="mt-3 max-w-2xl text-white/80">View learning evidence, add guidance notes, and monitor reviewed learning paths. Academic records remain read-only.</p></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(({label,value,icon:Icon})=><article key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><Icon className="h-6 w-6 text-indigo-700"/><p className="mt-4 text-3xl font-bold">{value}</p><p className="mt-1 text-sm text-slate-600">{label}</p></article>)}</section><section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Assigned students</h2><p className="mt-1 text-slate-600">Only active, current-year Mentor-plan assignments appear.</p></div><Link href="/mentor-dashboard/students" className="rounded-xl bg-indigo-700 px-5 py-3 font-bold text-white">View students</Link></div>{report.assignments.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{report.assignments.slice(0,6).map(({assignment,enrollment})=><Link key={assignment.id} href={`/mentor-dashboard/students/${assignment.student.id}`} className="rounded-xl border p-4 hover:border-indigo-300"><p className="font-bold">{assignment.student.name}</p><p className="mt-1 text-sm text-slate-500">{enrollment.schoolClass.name} · Section {enrollment.section.name}</p></Link>)}</div>:<p className="mt-5 rounded-xl bg-slate-50 p-5 text-slate-600">No eligible student assignment is active.</p>}</section><section className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Recent activity</h2>{report.recentActivity.length?<ul className="mt-4 space-y-3">{report.recentActivity.map(row=><li key={row.id} className="border-b pb-3 text-sm"><span className="font-semibold">{row.student.name}</span> · {row.type.replaceAll("_"," ").toLowerCase()}<br/><span className="text-slate-500">{row.createdAt.toLocaleString()}</span></li>)}</ul>:<p className="mt-4 text-slate-600">No mentor activity yet.</p>}</article><article className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Upcoming sessions</h2>{report.upcomingSessions.length?<ul className="mt-4 space-y-3">{report.upcomingSessions.map(row=><li key={row.id} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold">{row.student.name}</p><p className="text-sm text-slate-500">{row.scheduledAt.toLocaleString()}</p></li>)}</ul>:<p className="mt-4 text-slate-600">No sessions are scheduled. Live meetings, video, chat and calling are not part of this phase.</p>}</article></section></main>;
}
