import Link from "next/link";
import SchoolTeacherAssignmentManager from "@/components/school/SchoolTeacherAssignmentManager";
import SchoolTeacherAssignmentRemoveButton from "@/components/school/SchoolTeacherAssignmentRemoveButton";
import { getSchoolTeacherAssignmentWorkspace } from "@/lib/school-teacher-assignments";

export const dynamic = "force-dynamic";

export default async function TeacherAssignmentsPage({ searchParams }: { searchParams: Promise<{ q?: string; classId?: string; sectionId?: string; subjectId?: string; teacherId?: string }> }) {
  const params = await searchParams;
  const data = await getSchoolTeacherAssignmentWorkspace();
  const query = params.q?.trim().toLowerCase() ?? "";
  const rowSection = (row: (typeof data.assignments)[number]) => data.sections.find((section) => section.id === row.sectionId);
  const rows = data.assignments.filter((row) => (!query || [row.teacherName, row.className, row.sectionName, ...row.subjects].join(" ").toLowerCase().includes(query)) && (!params.classId || rowSection(row)?.classId === params.classId) && (!params.sectionId || row.sectionId === params.sectionId) && (!params.subjectId || row.subjectIds.includes(params.subjectId)));
  const selectedInitial = data.assignments.find((row) => row.teacherId === params.teacherId && row.sectionId === params.sectionId);
  const classes = Array.from(new Map(data.sections.map((section) => [section.classId, section.className])).entries());
  const subjects = Array.from(new Map(data.sections.flatMap((section) => section.subjects.map((subject) => [subject.subjectId, subject.name] as const))).entries());
  return <main className="space-y-5 p-4 text-[15px] sm:p-6 lg:p-8">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">Academics</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Teacher Assignments</h1><p className="mt-1 text-sm text-slate-600">Assign a teacher to one or more subjects. Book access follows the section subject mapping.</p></div><a href="#assign-teacher" className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white">+ Assign Teacher</a></header>
    <form className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-5"><input name="q" defaultValue={params.q} placeholder="Search teacher or subject" className="h-9 rounded-lg border border-slate-300 px-3 text-sm md:col-span-2"/><select name="classId" defaultValue={params.classId ?? ""} className="h-9 rounded-lg border border-slate-300 px-3 text-sm"><option value="">All classes</option>{classes.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select name="sectionId" defaultValue={params.sectionId ?? ""} className="h-9 rounded-lg border border-slate-300 px-3 text-sm"><option value="">All sections</option>{data.sections.map((section) => <option key={section.id} value={section.id}>{section.className} · {section.name}</option>)}</select><select name="subjectId" defaultValue={params.subjectId ?? ""} className="h-9 rounded-lg border border-slate-300 px-3 text-sm"><option value="">All subjects</option>{subjects.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><button className="h-9 rounded-lg bg-slate-900 px-3 text-sm font-bold text-white md:col-start-5">Filter</button></form>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><h2 className="font-bold text-slate-950">Current assignments</h2><span className="text-xs font-semibold text-slate-500">{rows.length} rows</span></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-2.5">Teacher</th><th className="px-4 py-2.5">Class</th><th className="px-4 py-2.5">Section</th><th className="px-4 py-2.5">Subjects</th><th className="px-4 py-2.5">Book status</th><th className="px-4 py-2.5">Class teacher</th><th className="px-4 py-2.5">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} className="align-middle"><td className="px-4 py-3 font-semibold text-slate-900">{row.teacherName}</td><td className="px-4 py-3">{row.className}</td><td className="px-4 py-3">{row.sectionName}</td><td className="max-w-[260px] px-4 py-3 text-slate-600">{row.subjects.join(", ") || "—"}</td><td className="px-4 py-3"><span className={"rounded-full px-2 py-1 text-xs font-bold " + (row.bookStatus === "Assigned" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700")}>{row.bookStatus}</span></td><td className="px-4 py-3">{row.classTeacher ? "Yes" : "No"}</td><td className="px-4 py-3"><div className="flex gap-3"><Link href={"/school-dashboard/teacher-assignments?teacherId=" + row.teacherId + "&sectionId=" + row.sectionId + "#assign-teacher"} className="font-bold text-blue-700 hover:underline">Edit</Link><SchoolTeacherAssignmentRemoveButton teacherId={row.teacherId} sectionId={row.sectionId}/></div></td></tr>)}</tbody></table></div> : <p className="px-4 py-10 text-center text-sm text-slate-500">No matching assignments.</p>}</section>
    <div id="assign-teacher"><SchoolTeacherAssignmentManager teachers={data.teachers} sections={data.sections} books={data.books} initial={selectedInitial ? { teacherId: selectedInitial.teacherId, sectionId: selectedInitial.sectionId, subjectIds: selectedInitial.subjectIds, classTeacher: selectedInitial.classTeacher } : undefined}/></div>
  </main>;
}
