"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { BookOpen, Eye, Pencil, Trash2 } from "lucide-react";
import type { BookTableItem } from "@/types/admin-book";

export default function BookTable({ books, filtered = false }: { books: BookTableItem[]; filtered?: boolean }) {
  const router = useRouter();
  async function deleteBook(book: BookTableItem) { if (!window.confirm(`Permanently delete “${book.title}” and its managed files?`)) return; const response = await fetch(`/api/admin/books/${book.id}`, { method: "DELETE" }); const body = await response.json().catch(() => ({})); if (!response.ok) return alert(body.message || "Unable to delete book."); router.refresh(); }
  if (!books.length) return <div className="rounded-2xl border bg-white py-16 text-center"><BookOpen className="mx-auto h-11 w-11 text-slate-300"/><h2 className="mt-4 text-xl font-semibold">{filtered ? "No matching books" : "No books yet"}</h2><p className="mt-2 text-slate-500">{filtered ? "Try clearing or changing the filters." : "Create the first publication to get started."}</p>{!filtered && <Link href="/admin/books/new" className="mt-5 inline-flex rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Add Book</Link>}</div>;
  return <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="min-w-[1500px] w-full text-sm"><thead className="bg-slate-50 text-left text-slate-600"><tr>{["Book","Slug","Class","Subject","Series","ISBN","Author","Edition","Price","Featured","Status","Created","Updated","Actions"].map((h) => <th key={h} className="whitespace-nowrap px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{books.map((book) => <tr key={book.id} className="border-t align-top hover:bg-slate-50"><td className="px-4 py-4"><div className="flex w-64 gap-3">{book.coverImage ? <Image src={book.coverImage} alt="" width={48} height={64} className="h-16 w-12 rounded object-cover"/> : <div className="flex h-16 w-12 items-center justify-center rounded bg-slate-100"><BookOpen className="h-5 w-5"/></div>}<div><p className="font-semibold text-slate-900">{book.title}</p><p className="line-clamp-2 text-xs text-slate-500">{book.subtitle || "—"}</p></div></div></td><Cell>{book.slug}</Cell><Cell>{book.class.name}</Cell><Cell>{book.subject.name}</Cell><Cell>{book.series?.name || "—"}</Cell><Cell>{book.isbn || "—"}</Cell><Cell>{book.author || "—"}</Cell><Cell>{book.edition || "—"}</Cell><Cell>{book.price ? `₹${book.price}` : "—"}</Cell><Cell><Badge tone={book.featured ? "green" : "slate"}>{book.featured ? "Yes" : "No"}</Badge></Cell><Cell><Badge tone={book.published ? "blue" : "amber"}>{book.published ? "Published" : "Draft"}</Badge></Cell><Cell>{formatDate(book.createdAt)}</Cell><Cell>{formatDate(book.updatedAt)}</Cell><td className="px-4 py-4"><div className="flex gap-2"><Link title="Preview" href={book.published ? `/books/${book.slug}` : `/admin/books/${book.id}/preview`} target="_blank" className="rounded-lg border p-2"><Eye className="h-4 w-4"/></Link><Link title="Edit" href={`/admin/books/${book.id}/edit`} className="rounded-lg border p-2"><Pencil className="h-4 w-4"/></Link><button title="Delete" onClick={() => deleteBook(book)} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div>;
}
function Cell({ children }: { children: React.ReactNode }) { return <td className="max-w-40 px-4 py-4 text-slate-700"><span className="line-clamp-2">{children}</span></td>; }
function Badge({ children, tone }: { children: React.ReactNode; tone: "green" | "slate" | "blue" | "amber" }) { const styles = { green: "bg-green-100 text-green-700", slate: "bg-slate-100 text-slate-600", blue: "bg-blue-100 text-blue-700", amber: "bg-amber-100 text-amber-700" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${styles[tone]}`}>{children}</span>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)); }
