import { GapBars, GapEmpty, GapHero, GapLink } from "@/components/gaps/GapVisuals";
import { getTeacherGaps } from "@/lib/gaps/teacher";
export const dynamic = "force-dynamic"; export const revalidate = 0;
export default async function TeacherGapsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const q = await searchParams; const one = (value: string | string[] | undefined) => typeof value === "string" ? value : undefined;
  const report = await getTeacherGaps({ severity: one(q.severity), status: one(q.status), subjectId: one(q.subject), sectionId: one(q.section), query: one(q.query) });
  const sections = [...new Map(report.assignments.map((row) => [row.sectionId, row.section])).entries()];
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
    <GapHero eyebrow="Your assigned classes" title="Student learning insights" description="Review learning areas that may need extra attention in your current classes."/>
    <form className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-3 xl:grid-cols-6"><input name="query" defaultValue={one(q.query)} placeholder="Student name" className="rounded-xl border px-3 py-2"/><select name="section" defaultValue={one(q.section) ?? ""} className="rounded-xl border px-3 py-2"><option value="">All assigned classes</option>{sections.map(([id,section])=><option key={id} value={id}>{section.schoolClass.name} · {section.name}</option>)}</select><select name="severity" defaultValue={one(q.severity) ?? ""} className="rounded-xl border px-3 py-2"><option value="">All severities</option>{["LOW","MODERATE","HIGH","CRITICAL"].map(x=><option key={x}>{x}</option>)}</select><select name="status" defaultValue={one(q.status) ?? ""} className="rounded-xl border px-3 py-2"><option value="">All statuses</option>{["OPEN","ACKNOWLEDGED","RESOLVED","DISMISSED"].map(x=><option key={x}>{x}</option>)}</select><select name="subject" defaultValue={one(q.subject) ?? ""} className="rounded-xl border px-3 py-2"><option value="">All assigned subjects</option>{report.assignments.filter(x=>x.subjectId).map(x=><option key={`${x.sectionId}-${x.subjectId}`} value={x.subjectId!}>{x.subject?.name}</option>)}</select><button className="rounded-xl bg-indigo-700 px-4 py-2 font-bold text-white">Apply filters</button></form>
    <div className="grid gap-5 xl:grid-cols-3"><GapBars title="Common chapters" rows={report.commonChapters}/><GapBars title="Common learning outcomes" rows={report.commonOutcomes}/><GapBars title="Common competencies" rows={report.commonCompetencies}/></div>
    {report.gaps.length ? <section className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{["Student","Class","Subject","Learning area","Signal","Status",""].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{report.gaps.map(gap=><tr key={gap.id} className="border-t"><td className="p-4 font-semibold">{gap.studentName}<br/><span className="text-xs text-slate-500">{gap.admissionNumber}</span></td><td className="p-4">{gap.className} · {gap.sectionName}</td><td className="p-4">{gap.subject}</td><td className="p-4">{gap.learningArea}</td><td className="p-4">{gap.severityLabel}</td><td className="p-4">{gap.status}</td><td className="p-4"><GapLink href={`/teacher-dashboard/gaps/${gap.id}`}>Review</GapLink></td></tr>)}</tbody></table></section> : <GapEmpty title="No matching learning gaps" message="Try adjusting the filters, or wait for sufficient scored evidence from assigned learners."/>}
  </main>;
}
