"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Pencil, Plus, Search, Trash2 } from "lucide-react";

type Row = { id:string; name:string; code:string; sortOrder:number; active:boolean; description?:string|null; dependencyCount?:number };

export default function MasterEntityList({title,apiBase,createHref,rows,includeDescription=false}:{title:string;apiBase:string;createHref:string;rows:Row[];includeDescription?:boolean}) {
  const router=useRouter(),[query,setQuery]=useState(""),[status,setStatus]=useState("all");
  const filtered=useMemo(()=>rows.filter(row=>`${row.name} ${row.code} ${row.description??""}`.toLowerCase().includes(query.toLowerCase())&&(status==="all"||(status==="active")===row.active)),[query,rows,status]);
  async function remove(id:string){if(!confirm(`Delete this ${title.toLowerCase()}?`))return;const response=await fetch(`${apiBase}/${id}`,{method:"DELETE"}),body=await response.json().catch(()=>({}));if(!response.ok){alert(body.message||`Unable to delete ${title.toLowerCase()}.`);return}router.refresh()}
  const actions=(row:Row)=><div className="flex justify-end gap-2"><Link aria-label={`Edit ${row.name}`} href={createHref.replace("/new",`/${row.id}/edit`)} className="rounded-lg border p-2 text-slate-700"><Pencil className="h-4 w-4"/></Link><button aria-label={`Delete ${row.name}`} type="button" onClick={()=>remove(row.id)} className="rounded-lg border p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></div>;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold text-slate-900">{title}</h1><p className="mt-2 text-slate-600">Manage {title.toLowerCase()} used across the platform.</p></div><Link href={createHref} className="inline-flex items-center rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white"><Plus className="mr-2 h-5 w-5"/>Add {title.slice(0,-1)}</Link></div>
    <div className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:grid-cols-[1fr_180px]"><label className="relative"><span className="sr-only">Search</span><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${title.toLowerCase()}`} className="w-full rounded-xl border py-3 pl-10 pr-4"/></label><select aria-label="Status" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border px-4"><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    {!filtered.length?<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-slate-500">No {title.toLowerCase()} match these filters.</div>:<><div className="grid gap-4 md:hidden">{filtered.map(row=><article key={row.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><div><h2 className="font-bold">{row.name}</h2><p className="text-sm text-slate-500">{row.code}</p></div><Status active={row.active}/></div>{includeDescription&&row.description?<p className="mt-3 text-sm text-slate-600">{row.description}</p>:null}<div className="mt-4">{actions(row)}</div></article>)}</div><div className="hidden overflow-hidden rounded-2xl border bg-white shadow-sm md:block"><table className="w-full"><thead className="bg-slate-50 text-left"><tr><th className="px-6 py-4">Name</th><th className="px-6 py-4">Code</th>{includeDescription?<th className="px-6 py-4">Description</th>:null}<th className="px-6 py-4">Order</th><th className="px-6 py-4">Status</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id} className="border-t"><td className="px-6 py-4 font-semibold">{row.name}</td><td className="px-6 py-4">{row.code}</td>{includeDescription?<td className="px-6 py-4 text-slate-600">{row.description||"—"}</td>:null}<td className="px-6 py-4">{row.sortOrder}</td><td className="px-6 py-4"><Status active={row.active}/></td><td className="px-6 py-4">{actions(row)}</td></tr>)}</tbody></table></div></>}
  </div>;
}
function Status({active}:{active:boolean}){return <span className={`rounded-full px-3 py-1 text-xs font-semibold ${active?"bg-emerald-100 text-emerald-700":"bg-slate-200 text-slate-600"}`}>{active?"Active":"Inactive"}</span>}
