"use server";
import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireUser } from "@/lib/authz";
import { prisma } from "@/lib/prisma";

const QUESTION_TYPES=["MCQ","FILL_BLANK","TRUE_FALSE","MATCH","MULTIPLE_SELECT","VERY_SHORT","SHORT","SHORT_ANSWER","LONG","LONG_ANSWER","ASSERTION_REASON","CASE_STUDY","CASE_BASED","COMPETENCY","HOTS","PRACTICAL_ACTIVITY"];

const text=(f:FormData,k:string)=>String(f.get(k)??"").trim();const num=(f:FormData,k:string)=>{const v=Number(f.get(k));return Number.isInteger(v)&&v>=0?v:null};const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
async function admin(){await requireUser(["ADMIN"])}
export async function saveChapter(bookId:string,chapterId:string|undefined,f:FormData){await admin();const title=text(f,"title"),chapterNumber=num(f,"chapterNumber");if(!title||chapterNumber===null||chapterNumber<1)throw new Error("Chapter number and title are required.");const startPage=num(f,"startPage"),endPage=num(f,"endPage");if(startPage!==null&&endPage!==null&&endPage<startPage)throw new Error("End page must not be before start page.");const data={chapterNumber,title,slug:slug(text(f,"slug")||title),startPage,endPage,extractedText:text(f,"extractedText")||null,reviewedText:text(f,"reviewedText")||null,summary:text(f,"summary")||null,keywords:text(f,"keywords").split(",").map(x=>x.trim()).filter(Boolean),approved:f.get("approved")==="on",sortOrder:num(f,"sortOrder")??chapterNumber};if(chapterId){const found=await prisma.bookChapter.findFirst({where:{id:chapterId,bookId},select:{id:true}});if(!found)throw new Error("Chapter not found.");await prisma.bookChapter.update({where:{id:chapterId},data});}else await prisma.bookChapter.create({data:{...data,bookId}});revalidatePath(`/admin/books/${bookId}`);redirect(`/admin/books/${bookId}/chapters`)}
export async function deleteChapter(bookId:string,chapterId:string){await admin();const chapter=await prisma.bookChapter.findFirst({where:{id:chapterId,bookId},select:{_count:{select:{questions:true,learningOutcomes:true,activities:true}}}});if(!chapter)throw new Error("Chapter not found.");if(chapter._count.questions+chapter._count.learningOutcomes+chapter._count.activities>0)throw new Error("Remove linked questions, outcomes, and activities before deleting this chapter.");await prisma.bookChapter.delete({where:{id:chapterId}});revalidatePath(`/admin/books/${bookId}/chapters`)}
export async function moveChapter(bookId:string,chapterId:string,direction:-1|1){await admin();const chapters=await prisma.bookChapter.findMany({where:{bookId},orderBy:[{sortOrder:"asc"},{chapterNumber:"asc"}],select:{id:true,sortOrder:true}});const index=chapters.findIndex(x=>x.id===chapterId),other=chapters[index+direction];if(index<0||!other)return;await prisma.$transaction([prisma.bookChapter.update({where:{id:chapterId},data:{sortOrder:other.sortOrder}}),prisma.bookChapter.update({where:{id:other.id},data:{sortOrder:chapters[index].sortOrder}})]);revalidatePath(`/admin/books/${bookId}/chapters`)}
export async function saveQuestion(bookId:string,questionId:string|undefined,f:FormData){await admin();const chapterId=text(f,"chapterId"),questionText=text(f,"questionText"),questionType=text(f,"questionType");const chapter=await prisma.bookChapter.findFirst({where:{id:chapterId,bookId},select:{id:true}});if(!chapter||!questionText||!QUESTION_TYPES.includes(questionType))throw new Error("Valid chapter, type, and question text are required.");const rawOptions=text(f,"options"),rawAnswer=text(f,"correctAnswer");let options:Prisma.InputJsonValue|typeof Prisma.JsonNull=Prisma.JsonNull,correctAnswer=rawAnswer||null;if(questionType==="MATCH"){const pairs=rawOptions.split("\n").map(line=>line.split("=>").map(part=>part.trim())).filter(parts=>parts.length===2&&parts.every(Boolean));if(pairs.length<2)throw new Error("Match questions need at least two lines in Left => Right format.");options={left:pairs.map(parts=>parts[0]),right:pairs.map(parts=>parts[1])};correctAnswer=JSON.stringify(Object.fromEntries(pairs));}else if(rawOptions){const values=rawOptions.split("\n").map(x=>x.trim()).filter(Boolean);options=values;if(questionType==="MULTIPLE_SELECT"){const selected=rawAnswer.split(/[\n,]/).map(x=>x.trim()).filter(Boolean);if(!selected.length||selected.some(answer=>!values.includes(answer)))throw new Error("Multiple-select answers must match the listed options.");correctAnswer=JSON.stringify(selected);}}const data={chapterId,questionType,questionText,options,correctAnswer,explanation:text(f,"explanation")||null,marks:Math.max(1,num(f,"marks")??1),difficulty:text(f,"difficulty")||"MEDIUM",bloomLevel:text(f,"bloomLevel")||null,competency:text(f,"competency")||null,approved:f.get("approved")==="on"};if(questionId){const found=await prisma.bookQuestion.findFirst({where:{id:questionId,bookId},select:{id:true}});if(!found)throw new Error("Question not found.");await prisma.bookQuestion.update({where:{id:questionId},data});}else await prisma.bookQuestion.create({data:{...data,bookId}});revalidatePath(`/admin/books/${bookId}/questions`);redirect(`/admin/books/${bookId}/questions`)}
export async function deleteQuestion(bookId:string,id:string){await admin();await prisma.bookQuestion.deleteMany({where:{id,bookId}});revalidatePath(`/admin/books/${bookId}/questions`)}
export async function saveOutcome(bookId:string,f:FormData){await admin();const chapterId=text(f,"chapterId"),outcome=text(f,"outcome"),id=text(f,"id");if(!outcome||!await prisma.bookChapter.findFirst({where:{id:chapterId,bookId},select:{id:true}}))throw new Error("Valid chapter and outcome are required.");const data={chapterId,outcome,bloomLevel:text(f,"bloomLevel")||null,competency:text(f,"competency")||null,sortOrder:num(f,"sortOrder")??0};if(id)await prisma.chapterLearningOutcome.updateMany({where:{id,chapter:{bookId}},data});else await prisma.chapterLearningOutcome.create({data});revalidatePath(`/admin/books/${bookId}/learning-outcomes`)}
export async function deleteOutcome(bookId:string,id:string){await admin();await prisma.chapterLearningOutcome.deleteMany({where:{id,chapter:{bookId}}});revalidatePath(`/admin/books/${bookId}/learning-outcomes`)}
export async function saveActivity(bookId:string,f:FormData){await admin();const chapterId=text(f,"chapterId"),title=text(f,"title"),objective=text(f,"objective"),instructions=text(f,"instructions"),id=text(f,"id");if(!title||!objective||!instructions||!await prisma.bookChapter.findFirst({where:{id:chapterId,bookId},select:{id:true}}))throw new Error("Chapter, title, objective, and instructions are required.");const data={chapterId,title,objective,instructions,materials:text(f,"materials")||null,durationMinutes:num(f,"durationMinutes"),groupType:text(f,"groupType")||null,expectedLearning:text(f,"expectedLearning")||null,assessment:text(f,"assessment")||null,safetyNotes:text(f,"safetyNotes")||null,approved:f.get("approved")==="on"};if(id)await prisma.chapterActivity.updateMany({where:{id,chapter:{bookId}},data});else await prisma.chapterActivity.create({data});revalidatePath(`/admin/books/${bookId}/activities`)}
export async function deleteActivity(bookId:string,id:string){await admin();await prisma.chapterActivity.deleteMany({where:{id,chapter:{bookId}}});revalidatePath(`/admin/books/${bookId}/activities`)}
