import { GapHero, GapLink } from "@/components/gaps/GapVisuals";
import { requireTeacherGap } from "@/lib/gaps/teacher";
import { FRIENDLY_GAP_SEVERITY } from "@/lib/gaps/policy";
import { recomputeGapAction, reviewGapAction } from "../actions";
export const dynamic = "force-dynamic"; export const revalidate = 0;
export default async function TeacherGapDetailPage({ params }: { params: Promise<{ gapId: string }> }) {
  const { gapId } = await params; const { gap, evidence } = await requireTeacherGap(gapId); const area = gap.skillLabel ?? gap.chapter?.title ?? gap.book?.title ?? gap.subject?.name ?? "Learning area";
  return <main className="space-y-7 p-4 sm:p-6 lg:p-8"><GapHero eyebrow={`${gap.student.name} · ${gap.subject?.name ?? "General learning"}`} title={area} description="Review the aggregate evidence and record a bounded, auditable decision."/><section className="rounded-2xl border bg-white p-6 shadow-sm"><p className="font-bold">{FRIENDLY_GAP_SEVERITY[gap.severity]} · {gap.status}</p><h2 className="mt-6 text-lg font-bold">Evidence</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{evidence.map(row=><div key={row.id} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold">{row.metricKey.replaceAll("_", " ")}</p><p className="mt-1 text-2xl font-black">{Math.round(row.metricValue)}{row.metricKey === "AI_SUPPORT_REQUESTS" ? "" : "%"}</p><p className="text-xs text-slate-500">Aggregate sample: {row.sampleSize ?? "context only"}</p></div>)}</div>{["OPEN","ACKNOWLEDGED"].includes(gap.status) ? <div className="mt-7 grid gap-5 lg:grid-cols-3">{["ACKNOWLEDGE","DISMISS","RESOLVE"].map(action=><form key={action} action={reviewGapAction} className="rounded-xl border p-4"><input type="hidden" name="gapId" value={gap.id}/><input type="hidden" name="action" value={action}/><p className="font-bold">{action.toLowerCase()}</p>{action !== "ACKNOWLEDGE" && <textarea required minLength={5} maxLength={500} name="reason" placeholder="Short review reason" className="mt-3 min-h-24 w-full rounded-lg border p-3"/>}<button className="mt-3 rounded-lg bg-indigo-700 px-4 py-2 font-bold text-white">Save review</button></form>)}</div> : null}<form action={recomputeGapAction} className="mt-6"><input type="hidden" name="gapId" value={gap.id}/><button className="rounded-lg border px-4 py-2 font-semibold">Refresh from stored analytics</button></form><h2 className="mt-7 text-lg font-bold">Review history</h2><ul className="mt-3 space-y-2">{gap.reviews.map(row=><li key={row.id} className="rounded-lg bg-slate-50 p-3 text-sm">{row.actor.name}: {row.action.toLowerCase()}{row.reason ? ` — ${row.reason}` : ""}</li>)}</ul><div className="mt-6"><GapLink href="/teacher-dashboard/gaps">Back to gap review</GapLink></div></section></main>;
}
