import Link from "next/link";
import { BookOpen, CalendarDays, GraduationCap, School, UserRoundCheck } from "lucide-react";
import { getSchoolAcademicHub } from "@/lib/school-dashboard";
export const dynamic="force-dynamic";
const tabs=["years","classes","subjects","assignments","content"] as const;
export default async function AcademicsPage({searchParams}:{searchParams:Promise<{tab?:string}>}){const params=await searchParams;const tab=tabs.includes(params.tab as typeof tabs[number])?params.tab as typeof tabs[number]:"years";const data=await getSchoolAcademicHub();return <main className="space-y-6 p-4 sm:p-6 lg:p-8"><header><h1 className="text-3xl font-bold">Academics</h1><p className="mt-2 text-slate-500">Academic structure, teaching ownership, and entitled learning content.</p></header><nav className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2">{tabs.map(item=><Link key={item} href={`/school-dashboard/academics?tab=${item}`} className={`whitespace-nowrap rounded-xl px-5 py-3 text-sm font-semibold capitalize ${tab===item?"bg-blue-600 text-white":"hover:bg-slate-50"}`}>{item==="years"?"Academic Year":item==="content"?"Books & Resources":item}</Link>)}</nav>
{tab==="years"&&<Section icon={CalendarDays} title="Academic Years" action="Manage academic years" href="/school-dashboard/academic-years">{data.years.map(item=><Row key={item.id} title={item.name} detail={`${item._count.classes} classes · ${item._count.enrollments} enrolments`} badge={item.current?"Current":item.active?"Active":"Inactive"}/>)}</Section>}
{tab==="classes"&&<Section icon={School} title="Classes & Sections" action="Manage classes" href="/school-dashboard/classes">{data.classes.map(item=><Row key={item.id} title={item.name} detail={`${item.sections.length} active sections`} badge="Active"/>)}</Section>}
{tab==="subjects"&&<Section icon={BookOpen} title="Subjects" action="Manage in classes" href="/school-dashboard/classes">{data.subjects.map(item=><Row key={item.id} title={item.name} detail={`Used across active sections`} badge="Active"/>)}</Section>}
{tab==="assignments"&&<Section icon={UserRoundCheck} title="Teacher Assignments" action="Manage assignments" href="/school-dashboard/teacher-assignments"><Summary value={data.assignments} label="active teacher assignments"/><p className="mt-4 text-sm text-slate-500">Class-teacher and subject-teacher ownership uses the existing scoped assignment workflow.</p></Section>}
{tab==="content"&&<Section icon={GraduationCap} title="Books & Resources"><div className="grid gap-4 sm:grid-cols-2"><Link href="/school-dashboard/books" className="rounded-2xl bg-blue-50 p-5"><strong className="text-2xl text-blue-700">{data.books}</strong><p className="mt-1 text-sm">active book adoptions</p></Link><Link href="/school-dashboard/resources" className="rounded-2xl bg-emerald-50 p-5"><strong className="text-2xl text-emerald-700">{data.resources}</strong><p className="mt-1 text-sm">active resource entitlements</p></Link></div></Section>}
</main>}
function Section({icon:Icon,title,action,href,children}:{icon:typeof School;title:string;action?:string;href?:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon/></span><h2 className="font-bold">{title}</h2></div>{action&&href&&<Link href={href} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">{action}</Link>}</div><div className="divide-y">{children}</div></section>}
function Row({title,detail,badge}:{title:string;detail:string;badge:string}){return <div className="flex items-center justify-between gap-3 py-4"><div><strong className="text-sm">{title}</strong><p className="mt-1 text-xs text-slate-500">{detail}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700">{badge}</span></div>}
function Summary({value,label}:{value:number;label:string}){return <div className="rounded-2xl bg-violet-50 p-6"><strong className="text-3xl text-violet-700">{value}</strong><p className="mt-1 text-sm text-violet-900">{label}</p></div>}
