import { BookOpenCheck, Brain, ChevronDown, ClipboardList, FileQuestion, GraduationCap, Medal, School, Sparkles } from "lucide-react";
import QuestionTypeSelector from "./QuestionTypeSelector";
import type { ExamType, PaperSettingsValue } from "./types";

const exams: { name: ExamType; description: string; marks: number; duration: number; icon: typeof School }[] = [
  { name: "Class Test", description: "A quick classroom check", marks: 20, duration: 30, icon: ClipboardList },
  { name: "Unit Test", description: "Assess one teaching unit", marks: 30, duration: 45, icon: BookOpenCheck },
  { name: "Periodic Test", description: "Regular school assessment", marks: 40, duration: 60, icon: FileQuestion },
  { name: "Half Yearly", description: "Mid-session examination", marks: 80, duration: 180, icon: School },
  { name: "Annual Examination", description: "Full-session examination", marks: 80, duration: 180, icon: GraduationCap },
  { name: "Practice Paper", description: "Revision and preparation", marks: 40, duration: 60, icon: Sparkles },
  { name: "Competency Assessment", description: "Application-focused paper", marks: 50, duration: 90, icon: Brain },
  { name: "Olympiad", description: "Challenging concept assessment", marks: 60, duration: 90, icon: Medal },
  { name: "Custom", description: "Choose every paper setting", marks: 40, duration: 60, icon: FileQuestion },
];
const marks=[20,30,40,50,60,70,80]; const input="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 outline-none focus:border-blue-500";

export default function PaperSettings({ value, onChange }: {value:PaperSettingsValue;onChange:(v:PaperSettingsValue)=>void}) {
  function selectExam(exam: typeof exams[number]) { onChange({...value,examType:exam.name,title:exam.name,totalMarks:exam.marks,duration:exam.duration}); }
  return <div className="space-y-9"><div><h3 className="text-lg font-bold">Exam type</h3><p className="mt-1 text-sm text-slate-500">Choose a familiar format to apply sensible defaults.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{exams.map(exam=>{const Icon=exam.icon,active=value.examType===exam.name;return <button type="button" key={exam.name} onClick={()=>selectExam(exam)} className={`flex min-h-28 items-start gap-4 rounded-2xl border p-4 text-left transition ${active?"border-blue-500 bg-blue-50 ring-2 ring-blue-100":"bg-white hover:border-slate-400"}`}><span className={`rounded-xl p-2.5 ${active?"bg-blue-600 text-white":"bg-slate-100 text-slate-600"}`}><Icon className="h-5 w-5"/></span><span><strong className="block">{exam.name}</strong><span className="mt-1 block text-sm text-slate-500">{exam.description}</span></span></button>})}</div></div>
  <div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold">Paper pattern<select className={input} value={value.pattern} onChange={e=>onChange({...value,pattern:e.target.value as PaperSettingsValue["pattern"]})}>{["CBSE Pattern","School Pattern","Bluegate Pattern","Custom"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-semibold">Paper title<input className={input} maxLength={160} value={value.title} onChange={e=>onChange({...value,title:e.target.value})}/></label></div>
  <div><h3 className="text-lg font-bold">Maximum marks</h3><div className="mt-4 flex flex-wrap gap-3">{marks.map(mark=><button type="button" key={mark} onClick={()=>onChange({...value,totalMarks:mark})} className={`min-h-12 min-w-16 rounded-xl px-5 font-bold ${value.totalMarks===mark?"bg-blue-600 text-white":"border bg-white"}`}>{mark}</button>)}<label className="flex items-center gap-2 rounded-xl border bg-white px-4 font-semibold">Custom<input aria-label="Custom maximum marks" type="number" min="1" max="500" value={marks.includes(value.totalMarks)?"":value.totalMarks} onChange={e=>onChange({...value,totalMarks:Number(e.target.value)})} className="w-20 py-3 outline-none"/></label></div></div>
  <div className="grid gap-7 md:grid-cols-2"><div><h3 className="text-lg font-bold">Duration</h3><div className="mt-3 flex gap-3">{(["auto","manual"] as const).map(mode=><button type="button" key={mode} onClick={()=>onChange({...value,durationMode:mode})} className={`min-h-12 rounded-xl px-5 font-semibold ${value.durationMode===mode?"bg-blue-600 text-white":"border bg-white"}`}>{mode==="auto"?"Auto":"Manual"}</button>)}</div>{value.durationMode==="manual"&&<label className="mt-3 block text-sm font-semibold">Minutes<input className={input} type="number" min="10" max="360" value={value.duration} onChange={e=>onChange({...value,duration:Number(e.target.value)})}/></label>} {value.durationMode==="auto"&&<p className="mt-3 text-sm text-slate-500">Recommended: {value.duration} minutes</p>}</div><div><h3 className="text-lg font-bold">Difficulty</h3><div className="mt-3 flex flex-wrap gap-3">{(["Easy","Balanced","Advanced"] as const).map(x=><button type="button" key={x} onClick={()=>onChange({...value,difficulty:x})} className={`min-h-12 rounded-xl px-5 font-semibold ${value.difficulty===x?"bg-blue-600 text-white":"border bg-white"}`}>{x}</button>)}</div></div></div>
  <div><h3 className="text-lg font-bold">Question distribution</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{[{auto:true,title:"Automatic",text:"Recommended — Bluegate balances the paper"},{auto:false,title:"Manual",text:"Choose question types and counts"}].map(item=><button type="button" key={item.title} onClick={()=>onChange({...value,autoDistribution:item.auto})} className={`rounded-2xl border p-5 text-left ${value.autoDistribution===item.auto?"border-blue-500 bg-blue-50":"bg-white"}`}><strong>{item.title}</strong><span className="mt-1 block text-sm text-slate-500">{item.text}</span></button>)}</div>{!value.autoDistribution&&<div className="mt-5"><QuestionTypeSelector selected={value.questionTypes} counts={value.questionCounts} auto={false} onToggle={type=>onChange({...value,questionTypes:value.questionTypes.includes(type)?value.questionTypes.filter(x=>x!==type):[...value.questionTypes,type]})} onCount={(type,count)=>onChange({...value,questionCounts:{...value.questionCounts,[type]:count}})}/></div>}</div>
  <details className="group rounded-2xl border bg-slate-50"><summary className="flex cursor-pointer list-none items-center justify-between p-5 font-bold">Advanced options <ChevronDown className="h-5 w-5 transition group-open:rotate-180"/></summary><div className="grid gap-3 border-t p-5 sm:grid-cols-2">{([['bloomDistribution','Bloom distribution'],['internalChoices','Internal choices'],['caseBasedQuestions','Case based questions'],['creativeQuestions','Creative questions'],['applicationQuestions','Application questions']] as const).map(([key,label])=><label key={key} className="flex min-h-12 items-center gap-3 rounded-xl bg-white p-4 font-semibold"><input type="checkbox" checked={value.advanced[key]} onChange={e=>onChange({...value,advanced:{...value.advanced,[key]:e.target.checked}})} className="h-5 w-5 accent-blue-600"/>{label}</label>)}<label className="rounded-xl bg-white p-4 text-sm font-semibold">Competency percentage<input type="number" min="0" max="100" value={value.advanced.competencyPercent} onChange={e=>onChange({...value,advanced:{...value.advanced,competencyPercent:Number(e.target.value)}})} className={input}/></label></div></details></div>;
}
