"use client";
import { useEffect, useMemo, useState, useTransition } from "react";
import { ArrowLeft, ArrowRight, Sparkles } from "lucide-react";
import { generateQuestionPaper } from "@/app/teacher-dashboard/ai/actions";
import BookSelector from "./BookSelector"; import ChapterSelector from "./ChapterSelector"; import GenerationProgress from "./GenerationProgress"; import PaperSettings from "./PaperSettings"; import ReviewPanel from "./ReviewPanel"; import WizardStep from "./WizardStep"; import type { PaperSettingsValue, WizardOptions } from "./types";
const labels=["Book","Chapters","Settings","Review","Generate"];
export default function QuestionPaperWizard({ options }: {options:WizardOptions}) { const [step,setStep]=useState(0),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[bookId,setBookId]=useState(""),[search,setSearch]=useState(""),[chapterIds,setChapterIds]=useState<string[]>([]),[message,setMessage]=useState(""),[progress,setProgress]=useState(0),[pending,startTransition]=useTransition(); const [settings,setSettings]=useState<PaperSettingsValue>({title:"Question Paper",totalMarks:40,duration:60,difficulty:"Medium",autoDistribution:true,questionTypes:["MCQ","Short","Long"],questionCounts:{MCQ:10,Short:5,Long:2}}); const book=options.books.find(x=>x.id===bookId); const valid=[Boolean(classId&&subjectId&&bookId),chapterIds.length>0,Boolean(settings.title.trim()&&settings.totalMarks>0&&settings.duration>=10&&settings.questionTypes.length),true,false]; const canNext=valid[step]??false;
  const [generationId,setGenerationId]=useState("");
  useEffect(()=>{const stored=sessionStorage.getItem("bluegate-question-paper-generation");const id=stored&&/^[a-zA-Z0-9_-]{16,64}$/.test(stored)?stored:crypto.randomUUID();sessionStorage.setItem("bluegate-question-paper-generation",id);setGenerationId(id)},[]);
  useEffect(()=>{if(!pending)return;setProgress(0);const timer=setInterval(()=>setProgress(p=>Math.min(p+1,4)),700);return()=>clearInterval(timer)},[pending]);
  const estimated=useMemo(()=>settings.autoDistribution?Math.max(settings.questionTypes.length,Math.ceil(settings.totalMarks/2)):settings.questionTypes.reduce((n,t)=>n+(settings.questionCounts[t]??1),0),[settings]);
  function chooseClass(v:string){setClassId(v);setBookId("");setChapterIds([])} function chooseSubject(v:string){setSubjectId(v);setBookId("");setChapterIds([])} function chooseBook(v:string){setBookId(v);setChapterIds([])}
  function generate(){if(!book||!generationId||pending)return;setMessage("");setStep(4);startTransition(async()=>{const result=await generateQuestionPaper({generationId,bookId:book.id,chapterIds,title:settings.title,totalMarks:settings.totalMarks,duration:settings.duration,difficulty:settings.difficulty,autoDistribution:settings.autoDistribution,questionTypes:settings.questionTypes,questionCounts:settings.questionCounts,estimatedQuestions:estimated});if(result.ok){sessionStorage.removeItem("bluegate-question-paper-generation");setProgress(5);setTimeout(()=>window.location.assign(result.draftUrl),500)}else{const nextId=crypto.randomUUID();sessionStorage.setItem("bluegate-question-paper-generation",nextId);setGenerationId(nextId);setMessage(result.message);setStep(3)}})}
  return <div className="space-y-6"><nav aria-label="Wizard progress" className="overflow-x-auto rounded-2xl border bg-white p-3"><ol className="flex min-w-[620px] items-center">{labels.map((label,index)=><li key={label} className="flex flex-1 items-center"><div className={`flex h-9 w-9 items-center justify-center rounded-full text-sm font-bold ${index<=step?"bg-blue-600 text-white":"bg-slate-100 text-slate-500"}`}>{index+1}</div><span className={`ml-2 text-sm font-semibold ${index<=step?"text-slate-900":"text-slate-400"}`}>{label}</span>{index<labels.length-1&&<div className={`mx-3 h-0.5 flex-1 ${index<step?"bg-blue-500":"bg-slate-200"}`}/>}</li>)}</ol></nav>
  {step===0&&<WizardStep title="Choose your book" description="Find the class, subject, and Bluegate book for this paper."><BookSelector classes={options.classes} subjects={options.subjects} books={options.books} classId={classId} subjectId={subjectId} bookId={bookId} search={search} onClass={chooseClass} onSubject={chooseSubject} onBook={chooseBook} onSearch={setSearch}/></WizardStep>}
  {step===1&&book&&<WizardStep title="Select chapters" description="Choose one or more AI-ready chapters."><ChapterSelector chapters={book.chapters} selected={chapterIds} onToggle={id=>setChapterIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id])}/></WizardStep>}
  {step===2&&<WizardStep title="Paper settings" description="Tell us what the paper should look like. We’ll handle the technical details."><PaperSettings value={settings} onChange={setSettings}/></WizardStep>}
  {step===3&&book&&<WizardStep title="Review and generate" description="Check your selections before using one daily AI generation."><ReviewPanel book={book} chapterIds={chapterIds} settings={settings} entitlement={options.entitlement}/></WizardStep>}
  {step===4&&<WizardStep title="Creating your paper" description="Keep this page open while Bluegate prepares your editable draft."><GenerationProgress progress={progress}/></WizardStep>}
  {message&&<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 font-semibold text-red-700">{message}</div>}
  {step<4&&<div className="flex items-center justify-between gap-4"><button type="button" disabled={step===0} onClick={()=>setStep(s=>s-1)} className="inline-flex items-center rounded-xl border bg-white px-5 py-3 font-semibold disabled:opacity-40"><ArrowLeft className="mr-2 h-4 w-4"/>Back</button>{step<3?<button type="button" disabled={!canNext} onClick={()=>setStep(s=>s+1)} className="inline-flex items-center rounded-xl bg-blue-600 px-6 py-3 font-bold text-white disabled:opacity-40">Next<ArrowRight className="ml-2 h-4 w-4"/></button>:<button type="button" disabled={pending||!generationId||!options.entitlement.canGenerate} onClick={generate} className="inline-flex min-h-12 items-center rounded-xl bg-blue-600 px-6 py-3 font-bold text-white disabled:opacity-40"><Sparkles className="mr-2 h-4 w-4"/>Generate Question Paper</button>}</div>}</div>;
}
