"use client";
import { useEffect, useMemo, useState, useTransition } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ListChecks, Sparkles } from "lucide-react";
import { generateQuestionPaper } from "@/app/teacher-dashboard/ai/actions";
import BookSelector from "./BookSelector"; import ChapterSelector from "./ChapterSelector"; import GenerationProgress from "./GenerationProgress"; import PaperSettings from "./PaperSettings"; import ReviewPanel from "./ReviewPanel"; import WizardStep from "./WizardStep"; import type { PaperSettingsValue, WizardOptions } from "./types";
const labels=["Select Book","Exam Setup","Review"];
const initialSettings:PaperSettingsValue={title:"Periodic Test",examType:"Periodic Test",pattern:"CBSE Pattern",totalMarks:40,durationMode:"auto",duration:60,difficulty:"Balanced",autoDistribution:true,questionTypes:["MCQ","Very Short","Short","Long","Competency Based"],questionCounts:{MCQ:10,"Very Short":5,Short:5,Long:2,"Competency Based":2},advanced:{bloomDistribution:false,internalChoices:true,caseBasedQuestions:false,competencyPercent:20,creativeQuestions:false,applicationQuestions:true}};

export default function QuestionPaperWizard({ options }: {options:WizardOptions}) { const [step,setStep]=useState(0),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[bookId,setBookId]=useState(""),[search,setSearch]=useState(""),[coverage,setCoverage]=useState<"whole"|"selected">("whole"),[selectedChapterIds,setSelectedChapterIds]=useState<string[]>([]),[settings,setSettings]=useState(initialSettings),[message,setMessage]=useState(""),[progress,setProgress]=useState(0),[pending,startTransition]=useTransition(),[generationId,setGenerationId]=useState(()=>typeof window==="undefined"?"":(()=>{const stored=sessionStorage.getItem("bluegate-question-paper-generation");return stored&&/^[a-zA-Z0-9_-]{16,64}$/.test(stored)?stored:crypto.randomUUID()})()); const book=options.books.find(x=>x.id===bookId); const readyChapterIds=useMemo(()=>book?.chapters.filter(c=>c.aiReady).map(c=>c.id)??[],[book]); const chapterIds=coverage==="whole"?readyChapterIds:selectedChapterIds; const estimated=useMemo(()=>settings.autoDistribution?Math.max(8,Math.ceil(settings.totalMarks/2)):settings.questionTypes.reduce((n,t)=>n+(settings.questionCounts[t]??1),0),[settings]); const canContinue=step===0?Boolean(book&&chapterIds.length):step===1?Boolean(settings.title.trim()&&settings.totalMarks>0&&settings.duration>=10&&(settings.autoDistribution||settings.questionTypes.length)):true;
  useEffect(()=>{if(typeof window!=="undefined"&&generationId){sessionStorage.setItem("bluegate-question-paper-generation",generationId)}},[generationId]);
  function chooseClass(v:string){setClassId(v);setBookId("");setSelectedChapterIds([])} function chooseSubject(v:string){setSubjectId(v);setBookId("");setSelectedChapterIds([])} function chooseBook(v:string){setBookId(v);setCoverage("whole");setSelectedChapterIds([])}
  function generate(){if(!book||!generationId||pending)return;setMessage("");setProgress(0);setStep(3);startTransition(async()=>{const result=await generateQuestionPaper({generationId,bookId:book.id,chapterIds,coverage,examType:settings.examType,pattern:settings.pattern,title:settings.title,totalMarks:settings.totalMarks,duration:settings.duration,difficulty:settings.difficulty,autoDistribution:settings.autoDistribution,questionTypes:settings.questionTypes,questionCounts:settings.questionCounts,estimatedQuestions:estimated,advanced:settings.advanced});if(result.ok){sessionStorage.removeItem("bluegate-question-paper-generation");setProgress(5);setTimeout(()=>window.location.assign(result.draftUrl),500)}else{const nextId=crypto.randomUUID();sessionStorage.setItem("bluegate-question-paper-generation",nextId);setGenerationId(nextId);setMessage(result.message);setStep(2)}})}
  return <div className="space-y-6"><nav aria-label="Builder progress" className="rounded-2xl border bg-white p-4"><ol className="grid grid-cols-3 gap-2">{labels.map((label,index)=><li key={label} className="flex items-center"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-sm font-bold ${index<=Math.min(step,2)?"bg-blue-600 text-white":"bg-slate-100 text-slate-500"}`}>{index<step||step===3?<CheckCircle2 className="h-5 w-5"/>:index+1}</span><span className={`ml-2 hidden text-sm font-semibold sm:block ${index<=Math.min(step,2)?"text-slate-900":"text-slate-400"}`}>{label}</span>{index<2&&<span className={`mx-2 h-0.5 flex-1 sm:mx-4 ${index<step?"bg-blue-500":"bg-slate-200"}`}/>}</li>)}</ol></nav>
  {step===0&&<WizardStep title="Select book and coverage" description="Choose the Bluegate book. Whole-book coverage uses every AI-ready chapter automatically."><BookSelector classes={options.classes} subjects={options.subjects} books={options.books} classId={classId} subjectId={subjectId} bookId={bookId} search={search} onClass={chooseClass} onSubject={chooseSubject} onBook={chooseBook} onSearch={setSearch}/>{book&&<div className="mt-8"><h3 className="text-lg font-bold">Coverage</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><CoverageCard active={coverage==="whole"} icon={BookOpen} title="Whole Book" description={`${readyChapterIds.length} AI-ready chapters · Recommended`} onClick={()=>setCoverage("whole")}/><CoverageCard active={coverage==="selected"} icon={ListChecks} title="Selected Chapters" description="Choose specific AI-ready chapters" onClick={()=>setCoverage("selected")}/></div>{coverage==="selected"&&<div className="mt-5"><ChapterSelector chapters={book.chapters} selected={selectedChapterIds} onToggle={id=>setSelectedChapterIds(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id])}/></div>}</div>}</WizardStep>}
  {step===1&&<WizardStep title="Build your examination" description="Choose the exam format and paper pattern. Recommended defaults keep setup quick."><PaperSettings value={settings} onChange={setSettings}/></WizardStep>}
  {step===2&&book&&<WizardStep title="Review your question paper" description="Confirm the paper details before using one daily generation."><ReviewPanel book={book} chapterIds={chapterIds} coverage={coverage} settings={settings} entitlement={options.entitlement}/></WizardStep>}
  {step===3&&<WizardStep title="Creating your question paper" description="Keep this page open while your editable draft is prepared."><GenerationProgress progress={progress}/></WizardStep>}
  {message&&<div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 font-semibold text-red-700">{message}</div>}
  {step<3&&<div className="flex items-center justify-between gap-4"><button type="button" disabled={step===0} onClick={()=>setStep(s=>s-1)} className="inline-flex min-h-12 items-center rounded-xl border bg-white px-5 py-3 font-semibold disabled:opacity-40"><ArrowLeft className="mr-2 h-4 w-4"/>Back</button>{step<2?<button type="button" disabled={!canContinue} onClick={()=>setStep(s=>s+1)} className="inline-flex min-h-12 items-center rounded-xl bg-blue-600 px-6 py-3 font-bold text-white disabled:opacity-40">Continue<ArrowRight className="ml-2 h-4 w-4"/></button>:<button type="button" disabled={pending||!generationId||!options.entitlement.canGenerate} onClick={generate} className="inline-flex min-h-12 items-center rounded-xl bg-blue-600 px-6 py-3 font-bold text-white disabled:opacity-40"><Sparkles className="mr-2 h-4 w-4"/>Generate Question Paper</button>}</div>}</div>;
}
function CoverageCard({active,icon:Icon,title,description,onClick}:{active:boolean;icon:typeof BookOpen;title:string;description:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={`flex min-h-24 items-center gap-4 rounded-2xl border p-5 text-left ${active?"border-blue-500 bg-blue-50 ring-2 ring-blue-100":"bg-white"}`}><span className={`rounded-xl p-3 ${active?"bg-blue-600 text-white":"bg-slate-100 text-slate-600"}`}><Icon className="h-6 w-6"/></span><span><strong className="block">{title}</strong><span className="mt-1 block text-sm text-slate-500">{description}</span></span></button>}
