import { getSchoolTeacherRequests } from "@/lib/onboarding-approvals";
import { reviewTeacherAction } from "./actions";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default async function TeacherRequestsPage() {
  const requests = await getSchoolTeacherRequests();
  return <main className="space-y-5 p-4 text-[15px] sm:p-6 lg:p-8">
    <header><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">People</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Registration Requests</h1><p className="mt-1 text-sm text-slate-600">Approve the school relationship first; classroom visibility still requires a Teacher Assignment.</p></header>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{requests.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-2.5">Name</th><th className="px-4 py-2.5">Email</th><th className="px-4 py-2.5">Requested profile</th><th className="px-4 py-2.5">Status</th><th className="px-4 py-2.5">Review</th></tr></thead><tbody className="divide-y divide-slate-100">{requests.map((request) => <tr key={request.id} className="align-top"><td className="px-4 py-3 font-semibold">{request.teacher.user.name}<span className="block text-xs font-normal text-slate-500">{request.teacher.designation}</span></td><td className="px-4 py-3 text-slate-600">{request.teacher.user.email}</td><td className="px-4 py-3 text-slate-600">{request.teacher.subject} · {request.teacher.classes}</td><td className="px-4 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{request.status}</span></td><td className="px-4 py-3"><form action={reviewTeacherAction} className="flex min-w-56 flex-wrap gap-2"><input type="hidden" name="requestId" value={request.id}/><input name="reason" placeholder="Reason if rejecting" className="h-8 w-full rounded-lg border border-slate-300 px-2 text-xs"/><button name="status" value="APPROVED" className="rounded-lg bg-emerald-700 px-2 py-1 text-xs font-bold text-white">Approve</button><button name="status" value="REJECTED" className="rounded-lg border border-rose-300 px-2 py-1 text-xs font-bold text-rose-700">Reject</button><button name="status" value="SUSPENDED" className="rounded-lg bg-slate-900 px-2 py-1 text-xs font-bold text-white">Suspend</button></form></td></tr>)}</tbody></table></div> : <p className="px-4 py-10 text-center text-sm text-slate-500">No registration requests.</p>}</section>
  </main>;
}
