import Link from "next/link";
import { Search, Users } from "lucide-react";
import { getStudents } from "@/lib/academic";
import { createStudent, setStudentActive } from "../academic-actions";

export const dynamic = "force-dynamic";
const input = "h-9 w-full rounded-lg border border-slate-300 px-3 text-sm";
type Params = { query?: string; year?: string; classId?: string; sectionId?: string; active?: "active" | "inactive"; login?: "enabled" | "disabled" };

export default async function StudentsPage({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams;
  const { students, years } = await getStudents({ query: params.query?.trim(), academicYearId: params.year, schoolClassId: params.classId, sectionId: params.sectionId, active: params.active, login: params.login });
  const classes = years.flatMap((year) => year.classes.map((item) => ({ id: item.id, yearName: year.name, name: item.name })));
  const sections = years.flatMap((year) => year.classes.flatMap((schoolClass) => schoolClass.sections.map((section) => ({ id: section.id, label: year.name + " · " + schoolClass.name + " · " + section.name }))));
  return <main className="space-y-5 p-4 text-[15px] sm:p-6 lg:p-8">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">People</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Students</h1><p className="mt-1 text-sm text-slate-600">Manage enrollment and login readiness. Book visibility follows current enrollment automatically.</p></div><div className="flex flex-wrap gap-2"><a href="#add-student" className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white">+ Add student</a><Link href="/school-dashboard/students/bulk-upload" className="rounded-lg border border-blue-200 bg-white px-4 py-2 text-sm font-bold text-blue-700">Bulk Upload</Link></div></header>
    <details id="add-student" className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><summary className="cursor-pointer text-sm font-bold text-blue-700">Add student</summary><form action={createStudent} className="mt-3 grid gap-3 md:grid-cols-4"><input name="admissionNumber" required placeholder="Admission number" className={input}/><input name="firstName" required placeholder="First name" className={input}/><input name="lastName" required placeholder="Last name" className={input}/><input name="displayName" placeholder="Display name (optional)" className={input}/><input name="dateOfBirth" type="date" className={input}/><input name="joinDate" type="date" required className={input}/><input name="email" type="email" placeholder="Email (optional)" className={input}/><input name="studentPhone" placeholder="Student phone (optional)" className={input}/><input name="guardianName" placeholder="Guardian name" className={input}/><input name="gender" placeholder="Gender (optional)" className={input}/><input name="rollNumber" placeholder="Roll number (optional)" className={input}/><input name="guardianPhone" required placeholder="Guardian phone" className={input}/><select name="academicYearId" required className={input}><option value="">Academic year</option>{years.map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</select><select name="schoolClassId" required className={input}><option value="">Class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.yearName} · {item.name}</option>)}</select><input type="hidden" name="active" value="on"/><select name="sectionId" required className={input}><option value="">Section</option>{sections.map((section) => <option key={section.id} value={section.id}>{section.label}</option>)}</select><button className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold text-white">Create student</button></form></details>
    <form className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-8"><div className="flex items-center gap-2 md:col-span-2"><Search className="h-4 w-4 text-slate-400"/><input name="query" defaultValue={params.query} placeholder="Search name or admission number" className="h-9 w-full rounded-lg border border-slate-300 px-3 text-sm"/></div><select name="year" defaultValue={params.year ?? ""} className={input}><option value="">All years</option>{years.map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</select><select name="classId" defaultValue={params.classId ?? ""} className={input}><option value="">All classes</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.yearName} · {item.name}</option>)}</select><select name="sectionId" defaultValue={params.sectionId ?? ""} className={input}><option value="">All sections</option>{sections.map((section) => <option key={section.id} value={section.id}>{section.label}</option>)}</select><select name="active" defaultValue={params.active ?? ""} className={input}><option value="">All status</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select name="login" defaultValue={params.login ?? ""} className={input}><option value="">All login states</option><option value="enabled">Login enabled</option><option value="disabled">Login not enabled</option></select><button className="rounded-lg bg-slate-900 px-3 text-sm font-bold text-white">Filter</button></form>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{students.length ? <div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-2.5">Name</th><th className="px-4 py-2.5">Identifier</th><th className="px-4 py-2.5">Class / section</th><th className="px-4 py-2.5">Login</th><th className="px-4 py-2.5">Status</th><th className="px-4 py-2.5">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{students.map((student) => { const enrollment = student.enrollments[0]; const loginEnabled = Boolean(student.userId); return <tr key={student.id}><td className="px-4 py-3 font-semibold">{student.displayName || student.name}</td><td className="px-4 py-3 text-slate-600">{student.admissionNumber}</td><td className="px-4 py-3 text-slate-600">{enrollment ? enrollment.schoolClass.name + " · " + enrollment.section.name : "Not enrolled"}</td><td className="px-4 py-3 text-slate-600">{loginEnabled ? "Enabled" : "Not enabled"}</td><td className="px-4 py-3"><span className={"rounded-full px-2 py-1 text-xs font-bold " + (student.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600")}>{student.active ? "Active" : "Inactive"}</span></td><td className="px-4 py-3"><div className="flex flex-wrap gap-2"><Link href={"/school-dashboard/students/" + student.id} className="font-bold text-blue-700">View / edit</Link><Link href={"/school-dashboard/students/" + student.id + "#move-student"} className="font-bold text-slate-600">Move</Link><form action={setStudentActive}><input type="hidden" name="studentId" value={student.id}/><input type="hidden" name="active" value={student.active ? "false" : "true"}/><button className="font-bold text-rose-700">{student.active ? "Deactivate" : "Activate"}</button></form></div></td></tr>; })}</tbody></table></div> : <div className="px-4 py-10 text-center"><Users className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-2 text-sm text-slate-500">No students found.</p></div>}</section>
  </main>;
}
